package br.inatel.viagens.view;

/**
 * @author Nathalya
 * 
 */
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;

public class TelaContinentes extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaContinentes() {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jPanel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelSelecao = new javax.swing.JLabel();
        jLabelAmericaNorte = new javax.swing.JLabel();
        jLabelAmericaSul = new javax.swing.JLabel();
        jLabelEuropa = new javax.swing.JLabel();
        jLabelAfrica = new javax.swing.JLabel();
        jLabelAsia = new javax.swing.JLabel();
        jLabelOceania = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuRoteiro = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemExibir = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemListaLugares = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(null);

        jLabelSelecao.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelSelecao.setText("Selecione o continente que deseja conhecer:");
        jPanel.add(jLabelSelecao);
        jLabelSelecao.setBounds(20, 20, 610, 30);

        jLabelAmericaNorte.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelAmericaNorte.setText("<html><center><u>América</u><br><u>do</u><br><u>Norte</u></center></html>");
        jLabelAmericaNorte.setToolTipText("");
        jLabelAmericaNorte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAmericaNorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAmericaNorteMouseClicked(evt);
            }
        });
        jPanel.add(jLabelAmericaNorte);
        jLabelAmericaNorte.setBounds(20, 270, 80, 80);

        jLabelAmericaSul.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelAmericaSul.setText("<html><center><u>América</u><br><u>do Sul</u></center></html>");
        jLabelAmericaSul.setToolTipText("");
        jLabelAmericaSul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAmericaSul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAmericaSulMouseClicked(evt);
            }
        });
        jPanel.add(jLabelAmericaSul);
        jLabelAmericaSul.setBounds(320, 400, 70, 80);

        jLabelEuropa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelEuropa.setText("<html><center><u>Europa</u></center></html>");
        jLabelEuropa.setToolTipText("");
        jLabelEuropa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEuropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEuropaMouseClicked(evt);
            }
        });
        jPanel.add(jLabelEuropa);
        jLabelEuropa.setBounds(340, 210, 70, 80);

        jLabelAfrica.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelAfrica.setText("<html><center><u>África</u></center></html>");
        jLabelAfrica.setToolTipText("");
        jLabelAfrica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAfrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAfricaMouseClicked(evt);
            }
        });
        jPanel.add(jLabelAfrica);
        jLabelAfrica.setBounds(600, 380, 60, 30);

        jLabelAsia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelAsia.setText("<html><center><u>Ásia</u></center></html>");
        jLabelAsia.setToolTipText("");
        jLabelAsia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAsia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAsiaMouseClicked(evt);
            }
        });
        jPanel.add(jLabelAsia);
        jLabelAsia.setBounds(860, 260, 60, 30);

        jLabelOceania.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelOceania.setText("<html><center><u>Oceania</u></center></html>");
        jLabelOceania.setToolTipText("");
        jLabelOceania.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelOceania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOceaniaMouseClicked(evt);
            }
        });
        jPanel.add(jLabelOceania);
        jLabelOceania.setBounds(690, 470, 60, 30);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\map.png")); // NOI18N
        jPanel.add(background);
        background.setBounds(-30, 0, 1020, 640);

        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuRoteiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\script.png")); // NOI18N
        jMenuRoteiro.setText("Roteiro");

        jMenuItemCriar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemCriar);

        jMenuItemExibir.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jMenuItemExibir.setText("Exibir");
        jMenuItemExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemExibir);

        jMenuBar.add(jMenuRoteiro);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");

        jMenuItemListaLugares.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\list.png")); // NOI18N
        jMenuItemListaLugares.setText("Lista de Lugares");
        jMenuItemListaLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaLugaresActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItemListaLugares);

        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.setToolTipText("");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        new TelaCriarRoteiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jMenuItemExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirActionPerformed
        new TelaExibirTodosRoteiros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemExibirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemListaLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaLugaresActionPerformed
        new TelaContinentes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemListaLugaresActionPerformed

    private void jLabelAmericaNorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAmericaNorteMouseClicked
        new TelaExibirLugares(1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelAmericaNorteMouseClicked

    private void jLabelAmericaSulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAmericaSulMouseClicked
        new TelaExibirLugares(2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelAmericaSulMouseClicked

    private void jLabelEuropaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEuropaMouseClicked
        new TelaExibirLugares(3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEuropaMouseClicked

    private void jLabelAfricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAfricaMouseClicked
        new TelaExibirLugares(4).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelAfricaMouseClicked

    private void jLabelOceaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOceaniaMouseClicked
        new TelaExibirLugares(5).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelOceaniaMouseClicked

    private void jLabelAsiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAsiaMouseClicked
        new TelaExibirLugares(6).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelAsiaMouseClicked

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContinentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabelAfrica;
    private javax.swing.JLabel jLabelAmericaNorte;
    private javax.swing.JLabel jLabelAmericaSul;
    private javax.swing.JLabel jLabelAsia;
    private javax.swing.JLabel jLabelEuropa;
    private javax.swing.JLabel jLabelOceania;
    private javax.swing.JLabel jLabelSelecao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemExibir;
    private javax.swing.JMenuItem jMenuItemListaLugares;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuRoteiro;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
