package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.RoteiroDAO;
import br.inatel.viagens.model.entities.Hospedagem;
import br.inatel.viagens.model.entities.Roteiro;
import br.inatel.viagens.model.entities.Transporte;
import java.awt.BorderLayout;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 * @author Nathalya
 * 
 */

public class TelaExibirRoteiro extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaExibirRoteiro(int id) {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
        
        jLabelNumRoteiro.setText(String.valueOf(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelRoteiro = new javax.swing.JLabel();
        jLabelNumRoteiro = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelDataIda = new javax.swing.JLabel();
        jLabelDataVolta = new javax.swing.JLabel();
        jLabelTransporte = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelPrecoTransporte = new javax.swing.JLabel();
        jLabelHorarioIda = new javax.swing.JLabel();
        jLabelHorarioVolta = new javax.swing.JLabel();
        jLabelHospedagem = new javax.swing.JLabel();
        jLabelNomeHospedagem = new javax.swing.JLabel();
        jLabelEnderecoHospedagem = new javax.swing.JLabel();
        jLabelCheckIn = new javax.swing.JLabel();
        jLabelCheckOut = new javax.swing.JLabel();
        jLabelPrecoHospedagem = new javax.swing.JLabel();
        jLabelRestaurante = new javax.swing.JLabel();
        jLabelPontosTuristicos = new javax.swing.JLabel();
        jLabelPassaporte = new javax.swing.JLabel();
        jLabelAviao = new javax.swing.JLabel();
        jLabelHotel = new javax.swing.JLabel();
        jLabelComida = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jLabelDestinoRoteiro = new javax.swing.JLabel();
        jLabelDataIdaRoteiro = new javax.swing.JLabel();
        jLabelDataVoltaRoteiro = new javax.swing.JLabel();
        jLabelTipoTransporte = new javax.swing.JLabel();
        jLabelHorarioIdaTransporte = new javax.swing.JLabel();
        jLabelHorarioVoltaTransporte = new javax.swing.JLabel();
        jLabelPrecoTransporteRoteiro = new javax.swing.JLabel();
        jLabelNomeHospedagemRoteiro = new javax.swing.JLabel();
        jLabelEnderecoHospedagemRoteiro = new javax.swing.JLabel();
        jLabelCheckInHospedagem = new javax.swing.JLabel();
        jLabelCheckOutHospedagem = new javax.swing.JLabel();
        jLabelPrecoHospedagemRoteiro = new javax.swing.JLabel();
        jLabelR$1 = new javax.swing.JLabel();
        jLabelR$2 = new javax.swing.JLabel();
        jPanelRestaurante = new javax.swing.JPanel();
        jScrollPaneRestaurante = new javax.swing.JScrollPane();
        jTableRestaurante = new javax.swing.JTable();
        jPanelPontoTuristico = new javax.swing.JPanel();
        jScrollPanePontoTuristico = new javax.swing.JScrollPane();
        jTablePontoTuristico = new javax.swing.JTable();
        jLabelPrecoTotal = new javax.swing.JLabel();
        jLabelR$3 = new javax.swing.JLabel();
        jLabelPrecoTotalRoteiro = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuRoteiro = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemExibir = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemListaLugares = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Roteiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabelRoteiro.setText("Roteiro");
        jFormattedText.add(jLabelRoteiro);
        jLabelRoteiro.setBounds(70, 0, 130, 60);

        jLabelNumRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jFormattedText.add(jLabelNumRoteiro);
        jLabelNumRoteiro.setBounds(190, 0, 70, 60);

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelInfo.setText("Informações da Viagem:");
        jFormattedText.add(jLabelInfo);
        jLabelInfo.setBounds(60, 75, 230, 30);

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelDestino.setText("Destino:");
        jFormattedText.add(jLabelDestino);
        jLabelDestino.setBounds(20, 120, 60, 30);

        jLabelDataIda.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelDataIda.setText("Data Ida:");
        jFormattedText.add(jLabelDataIda);
        jLabelDataIda.setBounds(20, 160, 70, 30);

        jLabelDataVolta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelDataVolta.setText("Data Volta:");
        jFormattedText.add(jLabelDataVolta);
        jLabelDataVolta.setBounds(230, 160, 80, 30);

        jLabelTransporte.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTransporte.setText("Transporte:");
        jFormattedText.add(jLabelTransporte);
        jLabelTransporte.setBounds(60, 200, 110, 30);

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTipo.setText("Tipo:");
        jFormattedText.add(jLabelTipo);
        jLabelTipo.setBounds(20, 240, 40, 30);

        jLabelPrecoTransporte.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelPrecoTransporte.setText("Preço:");
        jFormattedText.add(jLabelPrecoTransporte);
        jLabelPrecoTransporte.setBounds(20, 320, 50, 30);

        jLabelHorarioIda.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelHorarioIda.setText("Horário Ida:");
        jFormattedText.add(jLabelHorarioIda);
        jLabelHorarioIda.setBounds(20, 280, 80, 30);

        jLabelHorarioVolta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelHorarioVolta.setText("Horário Volta:");
        jFormattedText.add(jLabelHorarioVolta);
        jLabelHorarioVolta.setBounds(220, 280, 100, 30);

        jLabelHospedagem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelHospedagem.setText("Hospedagem:");
        jFormattedText.add(jLabelHospedagem);
        jLabelHospedagem.setBounds(60, 360, 140, 25);

        jLabelNomeHospedagem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNomeHospedagem.setText("Nome:");
        jFormattedText.add(jLabelNomeHospedagem);
        jLabelNomeHospedagem.setBounds(20, 400, 50, 30);

        jLabelEnderecoHospedagem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelEnderecoHospedagem.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoHospedagem);
        jLabelEnderecoHospedagem.setBounds(20, 440, 80, 30);

        jLabelCheckIn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCheckIn.setText("Check In:");
        jFormattedText.add(jLabelCheckIn);
        jLabelCheckIn.setBounds(20, 480, 60, 30);

        jLabelCheckOut.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCheckOut.setText("Check Out:");
        jFormattedText.add(jLabelCheckOut);
        jLabelCheckOut.setBounds(230, 480, 70, 30);

        jLabelPrecoHospedagem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelPrecoHospedagem.setText("Preço:");
        jFormattedText.add(jLabelPrecoHospedagem);
        jLabelPrecoHospedagem.setBounds(20, 520, 60, 30);

        jLabelRestaurante.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelRestaurante.setText("Restaurante:");
        jFormattedText.add(jLabelRestaurante);
        jLabelRestaurante.setBounds(530, 80, 130, 30);

        jLabelPontosTuristicos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPontosTuristicos.setText("Pontos Turísticos:");
        jFormattedText.add(jLabelPontosTuristicos);
        jLabelPontosTuristicos.setBounds(530, 310, 170, 25);

        jLabelPassaporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\passport.png")); // NOI18N
        jFormattedText.add(jLabelPassaporte);
        jLabelPassaporte.setBounds(20, 70, 50, 40);

        jLabelAviao.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\transportation.png")); // NOI18N
        jFormattedText.add(jLabelAviao);
        jLabelAviao.setBounds(20, 200, 30, 30);

        jLabelHotel.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\hotel.png")); // NOI18N
        jFormattedText.add(jLabelHotel);
        jLabelHotel.setBounds(20, 350, 30, 40);

        jLabelComida.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\localization.png")); // NOI18N
        jFormattedText.add(jLabelComida);
        jLabelComida.setBounds(490, 290, 30, 60);

        jLabelLocal.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\restaurant.png")); // NOI18N
        jFormattedText.add(jLabelLocal);
        jLabelLocal.setBounds(490, 80, 30, 30);

        jLabelDestinoRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelDestinoRoteiro);
        jLabelDestinoRoteiro.setBounds(80, 120, 300, 30);

        jLabelDataIdaRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelDataIdaRoteiro);
        jLabelDataIdaRoteiro.setBounds(90, 160, 90, 30);

        jLabelDataVoltaRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelDataVoltaRoteiro);
        jLabelDataVoltaRoteiro.setBounds(310, 160, 80, 30);

        jLabelTipoTransporte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelTipoTransporte);
        jLabelTipoTransporte.setBounds(60, 240, 330, 30);

        jLabelHorarioIdaTransporte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelHorarioIdaTransporte);
        jLabelHorarioIdaTransporte.setBounds(110, 280, 90, 30);

        jLabelHorarioVoltaTransporte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelHorarioVoltaTransporte);
        jLabelHorarioVoltaTransporte.setBounds(320, 280, 70, 30);

        jLabelPrecoTransporteRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelPrecoTransporteRoteiro);
        jLabelPrecoTransporteRoteiro.setBounds(90, 320, 90, 30);

        jLabelNomeHospedagemRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelNomeHospedagemRoteiro);
        jLabelNomeHospedagemRoteiro.setBounds(70, 400, 320, 30);

        jLabelEnderecoHospedagemRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelEnderecoHospedagemRoteiro);
        jLabelEnderecoHospedagemRoteiro.setBounds(90, 440, 300, 30);

        jLabelCheckInHospedagem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelCheckInHospedagem);
        jLabelCheckInHospedagem.setBounds(90, 480, 90, 30);

        jLabelCheckOutHospedagem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelCheckOutHospedagem);
        jLabelCheckOutHospedagem.setBounds(310, 480, 80, 30);

        jLabelPrecoHospedagemRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelPrecoHospedagemRoteiro);
        jLabelPrecoHospedagemRoteiro.setBounds(90, 520, 90, 30);

        jLabelR$1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelR$1.setText("R$");
        jFormattedText.add(jLabelR$1);
        jLabelR$1.setBounds(70, 320, 20, 30);

        jLabelR$2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelR$2.setText("R$");
        jFormattedText.add(jLabelR$2);
        jLabelR$2.setBounds(70, 520, 15, 30);

        jTableRestaurante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableRestaurante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRestaurante.setGridColor(new java.awt.Color(74, 39, 72));
        jTableRestaurante.setRowHeight(30);
        jTableRestaurante.setSelectionBackground(new java.awt.Color(74, 39, 72));
        jTableRestaurante.getTableHeader().setReorderingAllowed(false);
        jScrollPaneRestaurante.setViewportView(jTableRestaurante);

        javax.swing.GroupLayout jPanelRestauranteLayout = new javax.swing.GroupLayout(jPanelRestaurante);
        jPanelRestaurante.setLayout(jPanelRestauranteLayout);
        jPanelRestauranteLayout.setHorizontalGroup(
            jPanelRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanelRestauranteLayout.setVerticalGroup(
            jPanelRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jFormattedText.add(jPanelRestaurante);
        jPanelRestaurante.setBounds(490, 130, 490, 150);

        jTablePontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablePontoTuristico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePontoTuristico.setGridColor(new java.awt.Color(74, 39, 72));
        jTablePontoTuristico.setRowHeight(30);
        jTablePontoTuristico.setSelectionBackground(new java.awt.Color(74, 39, 72));
        jTablePontoTuristico.getTableHeader().setReorderingAllowed(false);
        jScrollPanePontoTuristico.setViewportView(jTablePontoTuristico);

        javax.swing.GroupLayout jPanelPontoTuristicoLayout = new javax.swing.GroupLayout(jPanelPontoTuristico);
        jPanelPontoTuristico.setLayout(jPanelPontoTuristicoLayout);
        jPanelPontoTuristicoLayout.setHorizontalGroup(
            jPanelPontoTuristicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePontoTuristico, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanelPontoTuristicoLayout.setVerticalGroup(
            jPanelPontoTuristicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePontoTuristico, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jFormattedText.add(jPanelPontoTuristico);
        jPanelPontoTuristico.setBounds(490, 360, 490, 150);

        jLabelPrecoTotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelPrecoTotal.setText("Preço total:");
        jFormattedText.add(jLabelPrecoTotal);
        jLabelPrecoTotal.setBounds(490, 520, 90, 30);

        jLabelR$3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelR$3.setText("R$");
        jFormattedText.add(jLabelR$3);
        jLabelR$3.setBounds(580, 520, 20, 30);

        jLabelPrecoTotalRoteiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jFormattedText.add(jLabelPrecoTotalRoteiro);
        jLabelPrecoTotalRoteiro.setBounds(600, 520, 70, 30);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonVoltar);
        jButtonVoltar.setBounds(893, 20, 90, 30);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuRoteiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\script.png")); // NOI18N
        jMenuRoteiro.setText("Roteiro");

        jMenuItemCriar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemCriar);

        jMenuItemExibir.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jMenuItemExibir.setText("Exibir");
        jMenuItemExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemExibir);

        jMenuBar.add(jMenuRoteiro);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");

        jMenuItemListaLugares.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\list.png")); // NOI18N
        jMenuItemListaLugares.setText("Lista de Lugares");
        jMenuItemListaLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaLugaresActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItemListaLugares);

        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirActionPerformed
        new TelaExibirTodosRoteiros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemExibirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Definir a quantidade de casas decimais do número real
        DecimalFormat df = new DecimalFormat("0.00");
        
        RoteiroDAO dao = new RoteiroDAO();
        
        dao.precoTotalViagem(Integer.parseInt(jLabelNumRoteiro.getText()));
        
        Roteiro roteiro = new Roteiro();
        
        roteiro = dao.buscarRoteiro(jLabelNumRoteiro.getText());
        
        jLabelDestinoRoteiro.setText(roteiro.getDestino());
        jLabelDataIdaRoteiro.setText(roteiro.getDataIda());
        jLabelDataVoltaRoteiro.setText(roteiro.getDataVolta());
        //df.format retorna uma string
        jLabelPrecoTotalRoteiro.setText(df.format(roteiro.getPrecoTotal()));
        
        Transporte transporte = new Transporte();
        
        transporte = dao.buscarTransporte(Integer.parseInt(jLabelNumRoteiro.getText()));
        
        jLabelTipoTransporte.setText(transporte.getTipo());
        jLabelHorarioIdaTransporte.setText(transporte.getHorarioIda());
        jLabelHorarioVoltaTransporte.setText(transporte.getHorarioVolta());
        jLabelPrecoTransporteRoteiro.setText(df.format(Double.parseDouble(transporte.getPreco())));
        
        Hospedagem hospedagem = new Hospedagem();
        
        hospedagem = dao.buscarHospedagem(Integer.parseInt(jLabelNumRoteiro.getText()));
        
        jLabelNomeHospedagemRoteiro.setText(hospedagem.getNome());
        jLabelEnderecoHospedagemRoteiro.setText(hospedagem.getEndereco());
        jLabelCheckInHospedagem.setText(hospedagem.getCheckIn());
        jLabelCheckOutHospedagem.setText(hospedagem.getCheckOut());
        jLabelPrecoHospedagemRoteiro.setText(df.format(Double.parseDouble(hospedagem.getPreco())));
        
        jTableRestaurante.setModel(dao.buscarRestaurante(jLabelNumRoteiro.getText()));
        
        //Esconder o ID dos restaurantes
        jTableRestaurante.getColumnModel().getColumn(0).setMinWidth(0);
        jTableRestaurante.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableRestaurante.getColumnModel().getColumn(0).setWidth(0);
        
        //Para o usuário não poder selecionar nenhum campo da tabela e editar
        jTableRestaurante.setEnabled(false);
        
        jTablePontoTuristico.setModel(dao.buscarPontoTuristico(jLabelNumRoteiro.getText()));
        
        jTablePontoTuristico.getColumnModel().getColumn(0).setMinWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(0).setMaxWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(0).setWidth(0);
        
        jTablePontoTuristico.getColumnModel().getColumn(3).setMinWidth(100);
        jTablePontoTuristico.getColumnModel().getColumn(3).setMaxWidth(100);
        jTablePontoTuristico.getColumnModel().getColumn(3).setWidth(100);
        
        jTablePontoTuristico.setEnabled(false);
        
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        new TelaCriarRoteiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        new TelaExibirTodosRoteiros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jMenuItemListaLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaLugaresActionPerformed
        new TelaContinentes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemListaLugaresActionPerformed

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibirRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibirRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibirRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibirRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JLabel jLabelAviao;
    private javax.swing.JLabel jLabelCheckIn;
    private javax.swing.JLabel jLabelCheckInHospedagem;
    private javax.swing.JLabel jLabelCheckOut;
    private javax.swing.JLabel jLabelCheckOutHospedagem;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelDataIda;
    private javax.swing.JLabel jLabelDataIdaRoteiro;
    private javax.swing.JLabel jLabelDataVolta;
    private javax.swing.JLabel jLabelDataVoltaRoteiro;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelDestinoRoteiro;
    private javax.swing.JLabel jLabelEnderecoHospedagem;
    private javax.swing.JLabel jLabelEnderecoHospedagemRoteiro;
    private javax.swing.JLabel jLabelHorarioIda;
    private javax.swing.JLabel jLabelHorarioIdaTransporte;
    private javax.swing.JLabel jLabelHorarioVolta;
    private javax.swing.JLabel jLabelHorarioVoltaTransporte;
    private javax.swing.JLabel jLabelHospedagem;
    private javax.swing.JLabel jLabelHotel;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelNomeHospedagem;
    private javax.swing.JLabel jLabelNomeHospedagemRoteiro;
    private javax.swing.JLabel jLabelNumRoteiro;
    private javax.swing.JLabel jLabelPassaporte;
    private javax.swing.JLabel jLabelPontosTuristicos;
    private javax.swing.JLabel jLabelPrecoHospedagem;
    private javax.swing.JLabel jLabelPrecoHospedagemRoteiro;
    private javax.swing.JLabel jLabelPrecoTotal;
    private javax.swing.JLabel jLabelPrecoTotalRoteiro;
    private javax.swing.JLabel jLabelPrecoTransporte;
    private javax.swing.JLabel jLabelPrecoTransporteRoteiro;
    private javax.swing.JLabel jLabelR$1;
    private javax.swing.JLabel jLabelR$2;
    private javax.swing.JLabel jLabelR$3;
    private javax.swing.JLabel jLabelRestaurante;
    private javax.swing.JLabel jLabelRoteiro;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoTransporte;
    private javax.swing.JLabel jLabelTransporte;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemExibir;
    private javax.swing.JMenuItem jMenuItemListaLugares;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuRoteiro;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JPanel jPanelPontoTuristico;
    private javax.swing.JPanel jPanelRestaurante;
    private javax.swing.JScrollPane jScrollPanePontoTuristico;
    private javax.swing.JScrollPane jScrollPaneRestaurante;
    private javax.swing.JTable jTablePontoTuristico;
    private javax.swing.JTable jTableRestaurante;
    // End of variables declaration//GEN-END:variables
}
