package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.ContaDAO;
import br.inatel.viagens.model.entities.Conta;
import br.inatel.viagens.model.entities.Usuario;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Nathalya
 * 
 */

public class TelaCadastro extends javax.swing.JFrame {
    //Creates new form TelaLogin    
    public TelaCadastro() {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        //Para não começar com um jText selecionado
        jPanel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCadastro = new javax.swing.JLabel();
        jTextFieldEntradaNome = new javax.swing.JTextField();
        jTextFieldEntradaEmail = new javax.swing.JTextField();
        jPasswordFieldEntradaSenha = new javax.swing.JPasswordField();
        jPasswordFieldEntradaConfirmarSenha = new javax.swing.JPasswordField();
        jCheckBoxMostrarSenha = new javax.swing.JCheckBox();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelTransparencia = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Cadastro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel.setBackground(new java.awt.Color(74, 39, 72));
        jPanel.setForeground(new java.awt.Color(74, 39, 72));
        jPanel.setLayout(null);

        jLabelBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\background.png")); // NOI18N
        jPanel.add(jLabelBackground);
        jLabelBackground.setBounds(-6, -6, 650, 660);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Travel around the");
        jPanel.add(jLabel1);
        jLabel1.setBounds(660, 20, 330, 63);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("World");
        jPanel.add(jLabel2);
        jLabel2.setBounds(770, 70, 110, 63);

        jLabelCadastro.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelCadastro.setText("Cadastro");
        jPanel.add(jLabelCadastro);
        jLabelCadastro.setBounds(780, 190, 100, 30);

        jTextFieldEntradaNome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldEntradaNome.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEntradaNome.setText("Nome");
        jTextFieldEntradaNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEntradaNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEntradaNomeFocusLost(evt);
            }
        });
        jPanel.add(jTextFieldEntradaNome);
        jTextFieldEntradaNome.setBounds(710, 230, 230, 30);

        jTextFieldEntradaEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldEntradaEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEntradaEmail.setText("E-mail");
        jTextFieldEntradaEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEntradaEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEntradaEmailFocusLost(evt);
            }
        });
        jPanel.add(jTextFieldEntradaEmail);
        jTextFieldEntradaEmail.setBounds(710, 270, 230, 30);

        jPasswordFieldEntradaSenha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordFieldEntradaSenha.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldEntradaSenha.setText("Senha");
        jPasswordFieldEntradaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldEntradaSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldEntradaSenhaFocusLost(evt);
            }
        });
        jPanel.add(jPasswordFieldEntradaSenha);
        jPasswordFieldEntradaSenha.setBounds(710, 310, 230, 30);

        jPasswordFieldEntradaConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordFieldEntradaConfirmarSenha.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldEntradaConfirmarSenha.setText("Senha");
        jPasswordFieldEntradaConfirmarSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldEntradaConfirmarSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldEntradaConfirmarSenhaFocusLost(evt);
            }
        });
        jPanel.add(jPasswordFieldEntradaConfirmarSenha);
        jPasswordFieldEntradaConfirmarSenha.setBounds(710, 350, 230, 30);

        jCheckBoxMostrarSenha.setText("Mostrar senha");
        jCheckBoxMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMostrarSenhaActionPerformed(evt);
            }
        });
        jPanel.add(jCheckBoxMostrarSenha);
        jCheckBoxMostrarSenha.setBounds(710, 390, 120, 23);

        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonCadastrar);
        jButtonCadastrar.setBounds(710, 430, 230, 30);

        jLabelTransparencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\transparencia.png")); // NOI18N
        jPanel.add(jLabelTransparencia);
        jLabelTransparencia.setBounds(690, 170, 270, 310);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonVoltar);
        jButtonVoltar.setBounds(780, 500, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEntradaEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEntradaEmailFocusGained
        if(jTextFieldEntradaEmail.getText().trim().equals("E-mail")){
            jTextFieldEntradaEmail.setText("");
            
            jTextFieldEntradaEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldEntradaEmailFocusGained

    private void jTextFieldEntradaEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEntradaEmailFocusLost
        if(jTextFieldEntradaEmail.getText().trim().equals("")){
            jTextFieldEntradaEmail.setText("E-mail");
            
            jTextFieldEntradaEmail.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextFieldEntradaEmailFocusLost

    private void jCheckBoxMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMostrarSenhaActionPerformed
        if(jCheckBoxMostrarSenha.isSelected()){
            jPasswordFieldEntradaSenha.setEchoChar((char)0); 
            jPasswordFieldEntradaConfirmarSenha.setEchoChar((char)0);
        }
        else{
            jPasswordFieldEntradaSenha.setEchoChar('*');
            jPasswordFieldEntradaConfirmarSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxMostrarSenhaActionPerformed

    private void jPasswordFieldEntradaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldEntradaSenhaFocusLost
        char[] senha = jPasswordFieldEntradaSenha.getPassword();
        
        if(senha.length == 0){
            jPasswordFieldEntradaSenha.setText("Senha");

            jPasswordFieldEntradaSenha.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jPasswordFieldEntradaSenhaFocusLost

    private void jPasswordFieldEntradaSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldEntradaSenhaFocusGained
        char[] senha = jPasswordFieldEntradaSenha.getPassword();
        char[] palavra = {'S', 'e', 'n', 'h', 'a'};
        
        if(Arrays.equals(senha, palavra)){
            jPasswordFieldEntradaSenha.setText("");
            
            jPasswordFieldEntradaSenha.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFieldEntradaSenhaFocusGained

    private void jTextFieldEntradaNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEntradaNomeFocusGained
        if(jTextFieldEntradaNome.getText().trim().equals("Nome")){
            jTextFieldEntradaNome.setText("");
            
            jTextFieldEntradaNome.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldEntradaNomeFocusGained

    private void jTextFieldEntradaNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEntradaNomeFocusLost
        if(jTextFieldEntradaNome.getText().trim().equals("")){
            jTextFieldEntradaNome.setText("Nome");
            
            jTextFieldEntradaNome.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextFieldEntradaNomeFocusLost

    private void jPasswordFieldEntradaConfirmarSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldEntradaConfirmarSenhaFocusGained
        char[] senha = jPasswordFieldEntradaConfirmarSenha.getPassword();
        char[] palavra = {'S', 'e', 'n', 'h', 'a'};
        
        if(Arrays.equals(senha, palavra)){
            jPasswordFieldEntradaConfirmarSenha.setText("");
            
            jPasswordFieldEntradaConfirmarSenha.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFieldEntradaConfirmarSenhaFocusGained

    private void jPasswordFieldEntradaConfirmarSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldEntradaConfirmarSenhaFocusLost
        char[] senha = jPasswordFieldEntradaConfirmarSenha.getPassword();
        
        if(senha.length == 0){
            jPasswordFieldEntradaConfirmarSenha.setText("Senha");

            jPasswordFieldEntradaConfirmarSenha.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jPasswordFieldEntradaConfirmarSenhaFocusLost

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        //Pegando os valores entrados pelo usuário e colocando eles em suas respectivas classes e atributos
        Usuario usuario = new Usuario();
        usuario.setNome(jTextFieldEntradaNome.getText());
        
        Conta conta = new Conta();
        conta.setEmail(jTextFieldEntradaEmail.getText());
        conta.setSenha(String.valueOf(jPasswordFieldEntradaSenha.getPassword()));
        conta.setConfirmarSenha(String.valueOf(jPasswordFieldEntradaConfirmarSenha.getPassword()));
       
        //Se o cadastro der certo, o usuário vai para a página de login
        ContaDAO dao = new ContaDAO();
        if(dao.cadastrarUsuario(usuario, conta)){
            new TelaLogin().setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem cadastrar?", "TextEditor", 0);
        
        if(i == 0){ 
            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxMostrarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelTransparencia;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordFieldEntradaConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldEntradaSenha;
    private javax.swing.JTextField jTextFieldEntradaEmail;
    private javax.swing.JTextField jTextFieldEntradaNome;
    // End of variables declaration//GEN-END:variables
}
