package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.LugaresDAO;
import br.inatel.viagens.model.entities.Lugares;
import br.inatel.viagens.model.entities.PontoTuristicoLugares;
import br.inatel.viagens.model.entities.Viagens;
import br.inatel.viagens.util.ConverterTipos;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * @author Nathalya
 * 
 */

public class TelaCriarMaisPontosTuristicosViagem extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaCriarMaisPontosTuristicosViagem(int pag) {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
        
        jLabelPag.setText(String.valueOf(pag));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelRoteiro = new javax.swing.JLabel();
        jLabelPontosTuristicos = new javax.swing.JLabel();
        jLabelNomePontoTuristico1 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico1 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico1 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico1 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico1 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico1 = new javax.swing.JTextField();
        jLabelGo = new javax.swing.JLabel();
        jLabelGoImagem = new javax.swing.JLabel();
        jLabelPonto = new javax.swing.JLabel();
        jButtonAdicionarPontoTuristico = new javax.swing.JButton();
        jLabelLatitude1 = new javax.swing.JLabel();
        jTextFieldEntradaLatitude1 = new javax.swing.JTextField();
        jLabelLongitude1 = new javax.swing.JLabel();
        jTextFieldEntradaLongitude1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNomePontoTuristico2 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico2 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico2 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico2 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico2 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico2 = new javax.swing.JTextField();
        jLabelLatitude2 = new javax.swing.JLabel();
        jTextFieldEntradaLatitude2 = new javax.swing.JTextField();
        jLabelLongitude2 = new javax.swing.JLabel();
        jTextFieldEntradaLongitude2 = new javax.swing.JTextField();
        jLabelNomePontoTuristico3 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico3 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico3 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico3 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico3 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico3 = new javax.swing.JTextField();
        jLabelLatitude3 = new javax.swing.JLabel();
        jTextFieldEntradaLatitude3 = new javax.swing.JTextField();
        jLabelLongitude3 = new javax.swing.JLabel();
        jTextFieldEntradaLongitude3 = new javax.swing.JTextField();
        jLabelPag = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuViagem = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Criar Roteiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabelRoteiro.setText("Para onde Viajar?");
        jFormattedText.add(jLabelRoteiro);
        jLabelRoteiro.setBounds(70, 0, 300, 60);

        jLabelPontosTuristicos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPontosTuristicos.setText("Pontos Turísticos:");
        jFormattedText.add(jLabelPontosTuristicos);
        jLabelPontosTuristicos.setBounds(60, 90, 170, 25);

        jLabelNomePontoTuristico1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico1.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico1);
        jLabelNomePontoTuristico1.setBounds(20, 130, 50, 30);

        jTextFieldEntradaNomePontoTuristico1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico1);
        jTextFieldEntradaNomePontoTuristico1.setBounds(80, 130, 310, 30);

        jLabelPrecoPontoTuristico1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico1.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico1);
        jLabelPrecoPontoTuristico1.setBounds(20, 210, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico1);
        jTextFieldEntradaPrecoPontoTuristico1.setBounds(80, 210, 90, 30);

        jLabelEnderecoPontoTuristico1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico1.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico1);
        jLabelEnderecoPontoTuristico1.setBounds(20, 170, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico1);
        jTextFieldEntradaEnderecoPontoTuristico1.setBounds(80, 170, 310, 30);

        jLabelGo.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelGo.setText("GO!");
        jLabelGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGo);
        jLabelGo.setBounds(870, 550, 50, 40);

        jLabelGoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\plane.png")); // NOI18N
        jLabelGoImagem.setText("jLabel1");
        jLabelGoImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoImagemMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGoImagem);
        jLabelGoImagem.setBounds(740, 400, 260, 190);

        jLabelPonto.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\localization.png")); // NOI18N
        jFormattedText.add(jLabelPonto);
        jLabelPonto.setBounds(20, 70, 30, 60);

        jButtonAdicionarPontoTuristico.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarPontoTuristico.setText("  Pontos Turísticos");
        jButtonAdicionarPontoTuristico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarPontoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPontoTuristicoActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarPontoTuristico);
        jButtonAdicionarPontoTuristico.setBounds(550, 300, 140, 30);

        jLabelLatitude1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLatitude1.setText("Latitude:");
        jFormattedText.add(jLabelLatitude1);
        jLabelLatitude1.setBounds(20, 250, 50, 30);

        jTextFieldEntradaLatitude1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLatitude1);
        jTextFieldEntradaLatitude1.setBounds(80, 250, 90, 30);

        jLabelLongitude1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLongitude1.setText("Longitude:");
        jFormattedText.add(jLabelLongitude1);
        jLabelLongitude1.setBounds(240, 250, 60, 30);

        jTextFieldEntradaLongitude1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLongitude1);
        jTextFieldEntradaLongitude1.setBounds(300, 250, 90, 30);
        jFormattedText.add(jSeparator1);
        jSeparator1.setBounds(20, 300, 370, 10);

        jLabelNomePontoTuristico2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico2.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico2);
        jLabelNomePontoTuristico2.setBounds(20, 320, 50, 30);

        jTextFieldEntradaNomePontoTuristico2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico2);
        jTextFieldEntradaNomePontoTuristico2.setBounds(80, 320, 310, 30);

        jLabelEnderecoPontoTuristico2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico2.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico2);
        jLabelEnderecoPontoTuristico2.setBounds(20, 360, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico2);
        jTextFieldEntradaEnderecoPontoTuristico2.setBounds(80, 360, 310, 30);

        jLabelPrecoPontoTuristico2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico2.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico2);
        jLabelPrecoPontoTuristico2.setBounds(20, 400, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico2);
        jTextFieldEntradaPrecoPontoTuristico2.setBounds(80, 400, 90, 30);

        jLabelLatitude2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLatitude2.setText("Latitude:");
        jFormattedText.add(jLabelLatitude2);
        jLabelLatitude2.setBounds(20, 440, 50, 30);

        jTextFieldEntradaLatitude2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLatitude2);
        jTextFieldEntradaLatitude2.setBounds(80, 440, 90, 30);

        jLabelLongitude2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLongitude2.setText("Longitude:");
        jFormattedText.add(jLabelLongitude2);
        jLabelLongitude2.setBounds(240, 440, 60, 30);

        jTextFieldEntradaLongitude2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLongitude2);
        jTextFieldEntradaLongitude2.setBounds(300, 440, 90, 30);

        jLabelNomePontoTuristico3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico3.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico3);
        jLabelNomePontoTuristico3.setBounds(550, 130, 50, 30);

        jTextFieldEntradaNomePontoTuristico3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico3);
        jTextFieldEntradaNomePontoTuristico3.setBounds(610, 130, 310, 30);

        jLabelEnderecoPontoTuristico3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico3.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico3);
        jLabelEnderecoPontoTuristico3.setBounds(550, 170, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico3);
        jTextFieldEntradaEnderecoPontoTuristico3.setBounds(610, 170, 310, 30);

        jLabelPrecoPontoTuristico3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico3.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico3);
        jLabelPrecoPontoTuristico3.setBounds(550, 210, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico3);
        jTextFieldEntradaPrecoPontoTuristico3.setBounds(610, 210, 90, 30);

        jLabelLatitude3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLatitude3.setText("Latitude:");
        jFormattedText.add(jLabelLatitude3);
        jLabelLatitude3.setBounds(550, 250, 50, 30);

        jTextFieldEntradaLatitude3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLatitude3);
        jTextFieldEntradaLatitude3.setBounds(610, 250, 90, 30);

        jLabelLongitude3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLongitude3.setText("Longitude:");
        jFormattedText.add(jLabelLongitude3);
        jLabelLongitude3.setBounds(770, 250, 60, 30);

        jTextFieldEntradaLongitude3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLongitude3);
        jTextFieldEntradaLongitude3.setBounds(830, 250, 90, 30);
        jFormattedText.add(jLabelPag);
        jLabelPag.setBounds(440, 30, 0, 0);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");
        jMenuViagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuViagemMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoMouseClicked
        LugaresDAO dao = new LugaresDAO();
        
        List<PontoTuristicoLugares> pontosTuristicos = new ArrayList<>();
        List<Double> latitude = new ArrayList<>();
        List<Double> longitude = new ArrayList<>();
        
        PontoTuristicoLugares pontoTuristico1 = new PontoTuristicoLugares();
        
        if(!jTextFieldEntradaNomePontoTuristico1.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico1.getText().equals("")){
            pontoTuristico1.setNome(jTextFieldEntradaNomePontoTuristico1.getText());
            pontoTuristico1.setEndereco(jTextFieldEntradaEnderecoPontoTuristico1.getText());
            pontoTuristico1.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico1.getText()));

            latitude.add(Double.parseDouble(jTextFieldEntradaLatitude1.getText()));
            longitude.add(Double.parseDouble(jTextFieldEntradaLongitude1.getText()));
            
            pontosTuristicos.add(pontoTuristico1);
        }
        
        PontoTuristicoLugares pontoTuristico2 = new PontoTuristicoLugares();
        
        if(!jTextFieldEntradaNomePontoTuristico2.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico2.getText().equals("")){
            pontoTuristico2.setNome(jTextFieldEntradaNomePontoTuristico2.getText());
            pontoTuristico2.setEndereco(jTextFieldEntradaEnderecoPontoTuristico2.getText());
            pontoTuristico2.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico2.getText()));

            latitude.add(Double.parseDouble(jTextFieldEntradaLatitude2.getText()));
            longitude.add(Double.parseDouble(jTextFieldEntradaLongitude2.getText()));
        
            pontosTuristicos.add(pontoTuristico2);
        }
        
        PontoTuristicoLugares pontoTuristico3 = new PontoTuristicoLugares();
        
        if(!jTextFieldEntradaNomePontoTuristico3.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico3.getText().equals("")){
            pontoTuristico3.setNome(jTextFieldEntradaNomePontoTuristico3.getText());
            pontoTuristico3.setEndereco(jTextFieldEntradaEnderecoPontoTuristico3.getText());
            pontoTuristico3.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico3.getText()));

            latitude.add(Double.parseDouble(jTextFieldEntradaLatitude3.getText()));
            longitude.add(Double.parseDouble(jTextFieldEntradaLongitude3.getText()));
        
            pontosTuristicos.add(pontoTuristico3);
        }
        
        if(!pontosTuristicos.isEmpty()){
            if(dao.registrarPontoTuristico(pontosTuristicos, latitude, longitude)){
                JOptionPane.showMessageDialog(null, "Ponto Turístico criado com sucesso!");

                int pag = Integer.parseInt(jLabelPag.getText());
                
                if(pag == 0){
                    new TelaImagem().setVisible(true);
                    this.dispose();
                }
                else{
                    new TelaListaLugaresAdmin().setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jLabelGoMouseClicked

    private void jLabelGoImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoImagemMouseClicked
        jLabelGoMouseClicked(evt);
    }//GEN-LAST:event_jLabelGoImagemMouseClicked

    private void jButtonAdicionarPontoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPontoTuristicoActionPerformed
       LugaresDAO dao = new LugaresDAO();
        
        List<PontoTuristicoLugares> pontosTuristicos = new ArrayList<>();
        List<Double> latitude = new ArrayList<>();
        List<Double> longitude = new ArrayList<>();
        
        PontoTuristicoLugares pontoTuristico1 = new PontoTuristicoLugares();
        
        if(!jTextFieldEntradaNomePontoTuristico1.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico1.getText().equals("")){
            pontoTuristico1.setNome(jTextFieldEntradaNomePontoTuristico1.getText());
            pontoTuristico1.setEndereco(jTextFieldEntradaEnderecoPontoTuristico1.getText());
            pontoTuristico1.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico1.getText()));

            latitude.add(Double.parseDouble(jTextFieldEntradaLatitude1.getText()));
            longitude.add(Double.parseDouble(jTextFieldEntradaLongitude1.getText()));
            
            pontosTuristicos.add(pontoTuristico1);
        }
        
        PontoTuristicoLugares pontoTuristico2 = new PontoTuristicoLugares();
        
        if(!jTextFieldEntradaNomePontoTuristico2.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico2.getText().equals("")){
            pontoTuristico2.setNome(jTextFieldEntradaNomePontoTuristico2.getText());
            pontoTuristico2.setEndereco(jTextFieldEntradaEnderecoPontoTuristico2.getText());
            pontoTuristico2.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico2.getText()));

            latitude.add(Double.parseDouble(jTextFieldEntradaLatitude2.getText()));
            longitude.add(Double.parseDouble(jTextFieldEntradaLongitude2.getText()));
        
            pontosTuristicos.add(pontoTuristico2);
        }
        
        PontoTuristicoLugares pontoTuristico3 = new PontoTuristicoLugares();
        
        if(!jTextFieldEntradaNomePontoTuristico3.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico3.getText().equals("")){
            pontoTuristico3.setNome(jTextFieldEntradaNomePontoTuristico3.getText());
            pontoTuristico3.setEndereco(jTextFieldEntradaEnderecoPontoTuristico3.getText());
            pontoTuristico3.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico3.getText()));

            latitude.add(Double.parseDouble(jTextFieldEntradaLatitude3.getText()));
            longitude.add(Double.parseDouble(jTextFieldEntradaLongitude3.getText()));
        
            pontosTuristicos.add(pontoTuristico3);
        }
        
        if(pontosTuristicos.size() == 3){
            if(dao.registrarPontoTuristico(pontosTuristicos, latitude, longitude)){
                JOptionPane.showMessageDialog(null, "Ponto Turístico criado com sucesso!");

                new TelaCriarMaisPontosTuristicosViagem(0).setVisible(true);

                this.dispose();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_jButtonAdicionarPontoTuristicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        JOptionPane.showMessageDialog(null, "Salve os pontos turísticos!");
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenuViagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuViagemMouseClicked
        JOptionPane.showMessageDialog(null, "Salve os pontos turísticos!");
    }//GEN-LAST:event_jMenuViagemMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        JOptionPane.showMessageDialog(null, "Salve os pontos turísticos!");
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisPontosTuristicosViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisPontosTuristicosViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisPontosTuristicosViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisPontosTuristicosViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarPontoTuristico;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico1;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico2;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico3;
    private javax.swing.JLabel jLabelGo;
    private javax.swing.JLabel jLabelGoImagem;
    private javax.swing.JLabel jLabelLatitude1;
    private javax.swing.JLabel jLabelLatitude2;
    private javax.swing.JLabel jLabelLatitude3;
    private javax.swing.JLabel jLabelLongitude1;
    private javax.swing.JLabel jLabelLongitude2;
    private javax.swing.JLabel jLabelLongitude3;
    private javax.swing.JLabel jLabelNomePontoTuristico1;
    private javax.swing.JLabel jLabelNomePontoTuristico2;
    private javax.swing.JLabel jLabelNomePontoTuristico3;
    private javax.swing.JLabel jLabelPag;
    private javax.swing.JLabel jLabelPonto;
    private javax.swing.JLabel jLabelPontosTuristicos;
    private javax.swing.JLabel jLabelPrecoPontoTuristico1;
    private javax.swing.JLabel jLabelPrecoPontoTuristico2;
    private javax.swing.JLabel jLabelPrecoPontoTuristico3;
    private javax.swing.JLabel jLabelRoteiro;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico1;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico2;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico3;
    private javax.swing.JTextField jTextFieldEntradaLatitude1;
    private javax.swing.JTextField jTextFieldEntradaLatitude2;
    private javax.swing.JTextField jTextFieldEntradaLatitude3;
    private javax.swing.JTextField jTextFieldEntradaLongitude1;
    private javax.swing.JTextField jTextFieldEntradaLongitude2;
    private javax.swing.JTextField jTextFieldEntradaLongitude3;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico1;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico2;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico3;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico1;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico2;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico3;
    // End of variables declaration//GEN-END:variables
}
