package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.LugaresDAO;
import br.inatel.viagens.model.entities.PontoTuristicoLugares;
import br.inatel.viagens.model.entities.Viagens;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Nathalya
 * 
 */

public class TelaExibirLugar extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaExibirLugar(String destino, int id, String idContinente, boolean admin) {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
        
        jLabelLugar.setText(destino);
        jLabelIdLugar.setText(String.valueOf(id));
        jLabelIdContinente.setText(idContinente);
        
        jLabelAdmin.setText(String.valueOf(admin));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelLugar = new javax.swing.JLabel();
        jLabelIdLugar = new javax.swing.JLabel();
        jLabelPontosTuristicos = new javax.swing.JLabel();
        jLabelAltaTemp = new javax.swing.JLabel();
        jPanelPontoTuristico = new javax.swing.JPanel();
        jScrollPanePontoTuristico = new javax.swing.JScrollPane();
        jTablePontoTuristico = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPaneAltaTemporada = new javax.swing.JScrollPane();
        jTextAreaAltaTemporada = new javax.swing.JTextArea();
        jLabelClima = new javax.swing.JLabel();
        jScrollPaneClima = new javax.swing.JScrollPane();
        jTextAreaClima = new javax.swing.JTextArea();
        jLabelIdContinente = new javax.swing.JLabel();
        jButtonGoogleMaps = new javax.swing.JButton();
        jLabelAdmin = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuRoteiro = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemExibir = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemListaLugares = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Roteiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelLugar.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jFormattedText.add(jLabelLugar);
        jLabelLugar.setBounds(70, 0, 360, 60);
        jFormattedText.add(jLabelIdLugar);
        jLabelIdLugar.setBounds(440, 20, 0, 0);

        jLabelPontosTuristicos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPontosTuristicos.setText("Pontos Turísticos:");
        jFormattedText.add(jLabelPontosTuristicos);
        jLabelPontosTuristicos.setBounds(530, 80, 170, 30);

        jLabelAltaTemp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelAltaTemp.setText("Alta Temporada:");
        jFormattedText.add(jLabelAltaTemp);
        jLabelAltaTemp.setBounds(20, 90, 110, 30);

        jTablePontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablePontoTuristico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço", "Preço", "Latitude", "Longitude"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePontoTuristico.setGridColor(new java.awt.Color(74, 39, 72));
        jTablePontoTuristico.setRowHeight(30);
        jTablePontoTuristico.setSelectionBackground(new java.awt.Color(74, 39, 72));
        jTablePontoTuristico.getTableHeader().setReorderingAllowed(false);
        jScrollPanePontoTuristico.setViewportView(jTablePontoTuristico);

        javax.swing.GroupLayout jPanelPontoTuristicoLayout = new javax.swing.GroupLayout(jPanelPontoTuristico);
        jPanelPontoTuristico.setLayout(jPanelPontoTuristicoLayout);
        jPanelPontoTuristicoLayout.setHorizontalGroup(
            jPanelPontoTuristicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPontoTuristicoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPanePontoTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPontoTuristicoLayout.setVerticalGroup(
            jPanelPontoTuristicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePontoTuristico, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        jFormattedText.add(jPanelPontoTuristico);
        jPanelPontoTuristico.setBounds(520, 130, 450, 380);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonVoltar);
        jButtonVoltar.setBounds(893, 20, 90, 30);

        jTextAreaAltaTemporada.setEditable(false);
        jTextAreaAltaTemporada.setColumns(20);
        jTextAreaAltaTemporada.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaAltaTemporada.setRows(5);
        jTextAreaAltaTemporada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jScrollPaneAltaTemporada.setViewportView(jTextAreaAltaTemporada);

        jFormattedText.add(jScrollPaneAltaTemporada);
        jScrollPaneAltaTemporada.setBounds(140, 90, 340, 190);

        jLabelClima.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelClima.setText("Clima:");
        jFormattedText.add(jLabelClima);
        jLabelClima.setBounds(20, 320, 50, 30);

        jTextAreaClima.setEditable(false);
        jTextAreaClima.setColumns(20);
        jTextAreaClima.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaClima.setRows(5);
        jTextAreaClima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jScrollPaneClima.setViewportView(jTextAreaClima);

        jFormattedText.add(jScrollPaneClima);
        jScrollPaneClima.setBounds(140, 320, 340, 190);
        jFormattedText.add(jLabelIdContinente);
        jLabelIdContinente.setBounds(410, 20, 0, 0);

        jButtonGoogleMaps.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\googleMaps.png")); // NOI18N
        jButtonGoogleMaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoogleMapsActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonGoogleMaps);
        jButtonGoogleMaps.setBounds(700, 80, 30, 30);
        jFormattedText.add(jLabelAdmin);
        jLabelAdmin.setBounds(500, 20, 0, 0);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuRoteiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\script.png")); // NOI18N
        jMenuRoteiro.setText("Roteiro");

        jMenuItemCriar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemCriar);

        jMenuItemExibir.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jMenuItemExibir.setText("Exibir");
        jMenuItemExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemExibir);

        jMenuBar.add(jMenuRoteiro);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");

        jMenuItemListaLugares.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\list.png")); // NOI18N
        jMenuItemListaLugares.setText("Lista de Lugares");
        jMenuItemListaLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaLugaresActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItemListaLugares);

        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirActionPerformed
        new TelaExibirTodosRoteiros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemExibirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int id = Integer.valueOf(jLabelIdLugar.getText());
        
        boolean admin = Boolean.parseBoolean(jLabelAdmin.getText());
        
        if(admin){
            jMenuBar.remove(jMenuRoteiro);
           
            jMenuBar.revalidate();
        }
        
        //Faz com que quando chegue no limite do camop de texto quebre a linha
        jTextAreaAltaTemporada.setLineWrap(true);
        jTextAreaClima.setLineWrap(true);
        
        LugaresDAO dao = new LugaresDAO();
        
        Viagens viagem = new Viagens();
        
        viagem = dao.buscarViagem(id);
        
        jTextAreaAltaTemporada.setText(viagem.getAltaTemporada());
        jTextAreaClima.setText(viagem.getClima());
        
        jTablePontoTuristico.setModel(dao.buscarPontoTuristico(Integer.parseInt(jLabelIdLugar.getText())));
        
        jTablePontoTuristico.getColumnModel().getColumn(0).setMinWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(0).setMaxWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(0).setWidth(0);
        
        jTablePontoTuristico.getColumnModel().getColumn(3).setMinWidth(100);
        jTablePontoTuristico.getColumnModel().getColumn(3).setMaxWidth(100);
        jTablePontoTuristico.getColumnModel().getColumn(3).setWidth(100);
        
        jTablePontoTuristico.getColumnModel().getColumn(4).setMinWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(4).setMaxWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(4).setWidth(0);
        
        jTablePontoTuristico.getColumnModel().getColumn(5).setMinWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(5).setMaxWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(5).setWidth(0);
      
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        new TelaCriarRoteiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        boolean admin = Boolean.parseBoolean(jLabelAdmin.getText());
        
        if(!admin){
            new TelaExibirLugares(Integer.parseInt(jLabelIdContinente.getText())).setVisible(true);
            this.dispose();
        }
        else{
            new TelaListaLugaresAdmin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jMenuItemListaLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaLugaresActionPerformed
        new TelaContinentes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemListaLugaresActionPerformed

    private void jButtonGoogleMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoogleMapsActionPerformed
        int linha = -1;
        int id;
        
        linha = jTablePontoTuristico.getSelectedRow();
        if(linha == -1)
            JOptionPane.showMessageDialog(null, "Nenhum ponto turístico foi selecionado!", "Erro!", JOptionPane.ERROR_MESSAGE);
        else{
            PontoTuristicoLugares.latitude = Double.parseDouble(String.valueOf(jTablePontoTuristico.getValueAt(linha, 4)).replace(',', '.'));
            PontoTuristicoLugares.longitude = Double.parseDouble(String.valueOf(jTablePontoTuristico.getValueAt(linha, 5)).replace(',', '.'));
        
            new GoogleMaps().setVisible(true);
        }
    }//GEN-LAST:event_jButtonGoogleMapsActionPerformed

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGoogleMaps;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelAltaTemp;
    private javax.swing.JLabel jLabelClima;
    private javax.swing.JLabel jLabelIdContinente;
    private javax.swing.JLabel jLabelIdLugar;
    private javax.swing.JLabel jLabelLugar;
    private javax.swing.JLabel jLabelPontosTuristicos;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemExibir;
    private javax.swing.JMenuItem jMenuItemListaLugares;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuRoteiro;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JPanel jPanelPontoTuristico;
    private javax.swing.JScrollPane jScrollPaneAltaTemporada;
    private javax.swing.JScrollPane jScrollPaneClima;
    private javax.swing.JScrollPane jScrollPanePontoTuristico;
    private javax.swing.JTable jTablePontoTuristico;
    private javax.swing.JTextArea jTextAreaAltaTemporada;
    private javax.swing.JTextArea jTextAreaClima;
    // End of variables declaration//GEN-END:variables
}
