package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.RoteiroDAO;
import br.inatel.viagens.model.entities.Restaurante;
import java.util.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Nathalya
 * 
 */

public class TelaCriarMaisRestaurantes extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaCriarMaisRestaurantes(int idRoteiro) {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
        
        jLabelIdRoteiro.setText(String.valueOf(idRoteiro));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelRoteiro = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jLabelRestaurante = new javax.swing.JLabel();
        jLabelNomeRestaurante1 = new javax.swing.JLabel();
        jTextFieldEntradaNomeRestaurante1 = new javax.swing.JTextField();
        jLabelEnderecoRestaurante1 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoRestaurante1 = new javax.swing.JTextField();
        jSeparator = new javax.swing.JSeparator();
        jLabelNomeRestaurante2 = new javax.swing.JLabel();
        jTextFieldEntradaNomeRestaurante2 = new javax.swing.JTextField();
        jLabelEnderecoRestaurante2 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoRestaurante2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNomeRestaurante3 = new javax.swing.JLabel();
        jTextFieldEntradaNomeRestaurante3 = new javax.swing.JTextField();
        jLabelEnderecoRestaurante3 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoRestaurante3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelNomeRestaurante4 = new javax.swing.JLabel();
        jTextFieldEntradaNomeRestaurante4 = new javax.swing.JTextField();
        jLabelEnderecoRestaurante4 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoRestaurante4 = new javax.swing.JTextField();
        jLabelNomeRestaurante5 = new javax.swing.JLabel();
        jLabelEnderecoRestaurante5 = new javax.swing.JLabel();
        jTextFieldEntradaNomeRestaurante5 = new javax.swing.JTextField();
        jTextFieldEntradaEnderecoRestaurante5 = new javax.swing.JTextField();
        jButtonAdicionarRestaurante = new javax.swing.JButton();
        jLabelGo = new javax.swing.JLabel();
        jLabelGoImagem = new javax.swing.JLabel();
        jButtonAdicionarPontoTuristico = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelIdRoteiro = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuRoteiro = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemExibir = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemListaLugares = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Restaurantes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabelRoteiro.setText("Roteiro");
        jFormattedText.add(jLabelRoteiro);
        jLabelRoteiro.setBounds(70, 0, 130, 60);

        jLabelLocal.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\restaurant.png")); // NOI18N
        jFormattedText.add(jLabelLocal);
        jLabelLocal.setBounds(20, 80, 30, 30);

        jLabelRestaurante.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelRestaurante.setText("Restaurante:");
        jFormattedText.add(jLabelRestaurante);
        jLabelRestaurante.setBounds(60, 80, 130, 25);

        jLabelNomeRestaurante1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomeRestaurante1.setText("Nome:");
        jFormattedText.add(jLabelNomeRestaurante1);
        jLabelNomeRestaurante1.setBounds(20, 120, 50, 30);

        jTextFieldEntradaNomeRestaurante1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomeRestaurante1);
        jTextFieldEntradaNomeRestaurante1.setBounds(80, 120, 310, 30);

        jLabelEnderecoRestaurante1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoRestaurante1.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoRestaurante1);
        jLabelEnderecoRestaurante1.setBounds(20, 160, 60, 30);

        jTextFieldEntradaEnderecoRestaurante1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoRestaurante1);
        jTextFieldEntradaEnderecoRestaurante1.setBounds(80, 160, 310, 30);
        jFormattedText.add(jSeparator);
        jSeparator.setBounds(20, 220, 370, 10);

        jLabelNomeRestaurante2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomeRestaurante2.setText("Nome:");
        jFormattedText.add(jLabelNomeRestaurante2);
        jLabelNomeRestaurante2.setBounds(20, 250, 50, 30);

        jTextFieldEntradaNomeRestaurante2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomeRestaurante2);
        jTextFieldEntradaNomeRestaurante2.setBounds(80, 250, 310, 30);

        jLabelEnderecoRestaurante2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoRestaurante2.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoRestaurante2);
        jLabelEnderecoRestaurante2.setBounds(20, 290, 60, 30);

        jTextFieldEntradaEnderecoRestaurante2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoRestaurante2);
        jTextFieldEntradaEnderecoRestaurante2.setBounds(80, 290, 310, 30);
        jFormattedText.add(jSeparator1);
        jSeparator1.setBounds(20, 350, 370, 10);

        jLabelNomeRestaurante3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomeRestaurante3.setText("Nome:");
        jFormattedText.add(jLabelNomeRestaurante3);
        jLabelNomeRestaurante3.setBounds(20, 380, 50, 30);

        jTextFieldEntradaNomeRestaurante3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomeRestaurante3);
        jTextFieldEntradaNomeRestaurante3.setBounds(80, 380, 310, 30);

        jLabelEnderecoRestaurante3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoRestaurante3.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoRestaurante3);
        jLabelEnderecoRestaurante3.setBounds(20, 420, 60, 30);

        jTextFieldEntradaEnderecoRestaurante3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoRestaurante3);
        jTextFieldEntradaEnderecoRestaurante3.setBounds(80, 420, 310, 30);
        jFormattedText.add(jSeparator2);
        jSeparator2.setBounds(560, 220, 370, 10);

        jLabelNomeRestaurante4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomeRestaurante4.setText("Nome:");
        jFormattedText.add(jLabelNomeRestaurante4);
        jLabelNomeRestaurante4.setBounds(560, 120, 50, 30);

        jTextFieldEntradaNomeRestaurante4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomeRestaurante4);
        jTextFieldEntradaNomeRestaurante4.setBounds(620, 120, 310, 30);

        jLabelEnderecoRestaurante4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoRestaurante4.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoRestaurante4);
        jLabelEnderecoRestaurante4.setBounds(560, 160, 60, 30);

        jTextFieldEntradaEnderecoRestaurante4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoRestaurante4);
        jTextFieldEntradaEnderecoRestaurante4.setBounds(620, 160, 310, 30);

        jLabelNomeRestaurante5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomeRestaurante5.setText("Nome:");
        jFormattedText.add(jLabelNomeRestaurante5);
        jLabelNomeRestaurante5.setBounds(560, 250, 50, 30);

        jLabelEnderecoRestaurante5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoRestaurante5.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoRestaurante5);
        jLabelEnderecoRestaurante5.setBounds(560, 290, 60, 30);

        jTextFieldEntradaNomeRestaurante5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomeRestaurante5);
        jTextFieldEntradaNomeRestaurante5.setBounds(620, 250, 310, 30);

        jTextFieldEntradaEnderecoRestaurante5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoRestaurante5);
        jTextFieldEntradaEnderecoRestaurante5.setBounds(620, 290, 310, 30);

        jButtonAdicionarRestaurante.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarRestaurante.setText(" Restaurantes");
        jButtonAdicionarRestaurante.setBorder(null);
        jButtonAdicionarRestaurante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarRestauranteActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarRestaurante);
        jButtonAdicionarRestaurante.setBounds(560, 350, 150, 30);

        jLabelGo.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelGo.setText("GO!");
        jLabelGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGo);
        jLabelGo.setBounds(870, 550, 50, 40);

        jLabelGoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\plane.png")); // NOI18N
        jLabelGoImagem.setText("jLabel1");
        jLabelGoImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoImagemMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGoImagem);
        jLabelGoImagem.setBounds(740, 400, 260, 190);

        jButtonAdicionarPontoTuristico.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarPontoTuristico.setText(" Pontos Turísticos");
        jButtonAdicionarPontoTuristico.setBorder(null);
        jButtonAdicionarPontoTuristico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarPontoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPontoTuristicoActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarPontoTuristico);
        jButtonAdicionarPontoTuristico.setBounds(560, 390, 150, 30);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonVoltar);
        jButtonVoltar.setBounds(840, 20, 90, 30);
        jFormattedText.add(jLabelIdRoteiro);
        jLabelIdRoteiro.setBounds(200, 20, 0, 0);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuRoteiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\script.png")); // NOI18N
        jMenuRoteiro.setText("Roteiro");

        jMenuItemCriar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemCriar);

        jMenuItemExibir.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jMenuItemExibir.setText("Exibir");
        jMenuItemExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemExibir);

        jMenuBar.add(jMenuRoteiro);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");

        jMenuItemListaLugares.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\list.png")); // NOI18N
        jMenuItemListaLugares.setText("Lista de Lugares");
        jMenuItemListaLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaLugaresActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItemListaLugares);

        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGoImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoImagemMouseClicked
        Restaurante restaurante = new Restaurante();
        
        List<Restaurante> restaurantes = new ArrayList<>();
        
        if(!jTextFieldEntradaNomeRestaurante1.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante1.getText().equals("")){
            //Se não fizer isso vai adicionar a mesma instância na lista, ou seja, os valores da lista sempre será o último valor adicionado
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante1.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante1.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante2.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante2.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante2.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante2.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante3.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante3.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante3.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante3.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante4.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante4.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante4.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante4.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante5.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante5.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante5.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante5.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!restaurantes.isEmpty()){
            RoteiroDAO dao = new RoteiroDAO();
            
            if(dao.registrarRestaurante(Integer.parseInt(jLabelIdRoteiro.getText()), restaurantes)){
                JOptionPane.showMessageDialog(null, "Restaurante(s) criado(s) com sucesso!");
                
                new TelaInicial().setVisible(true);
            
                this.dispose();
            }
        }
        else{
            new TelaInicial().setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jLabelGoImagemMouseClicked

    private void jLabelGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoMouseClicked
        jLabelGoImagemMouseClicked(evt);
    }//GEN-LAST:event_jLabelGoMouseClicked

    private void jButtonAdicionarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarRestauranteActionPerformed
        Restaurante restaurante = new Restaurante();
        
        List<Restaurante> restaurantes = new ArrayList<>();
        
        if(!jTextFieldEntradaNomeRestaurante1.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante1.getText().equals("")){
            //Se não fizer isso vai adicionar a mesma instância na lista, ou seja, os valores da lista sempre será o último valor adicionado
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante1.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante1.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante2.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante2.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante2.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante2.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante3.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante3.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante3.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante3.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante4.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante4.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante4.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante4.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante5.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante5.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante5.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante5.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(restaurantes.size() == 5){
            RoteiroDAO dao = new RoteiroDAO();
            
            if(dao.registrarRestaurante(Integer.parseInt(jLabelIdRoteiro.getText()), restaurantes)){
                JOptionPane.showMessageDialog(null, "Restaurante(s) criado(s) com sucesso!");
                
                new TelaCriarMaisRestaurantes(Integer.parseInt(jLabelIdRoteiro.getText())).setVisible(true);

                this.dispose();
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
    }//GEN-LAST:event_jButtonAdicionarRestauranteActionPerformed

    private void jButtonAdicionarPontoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPontoTuristicoActionPerformed
        Restaurante restaurante = new Restaurante();
        
        List<Restaurante> restaurantes = new ArrayList<>();
        
        if(!jTextFieldEntradaNomeRestaurante1.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante1.getText().equals("")){
            //Se não fizer isso vai adicionar a mesma instância na lista, ou seja, os valores da lista sempre será o último valor adicionado
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante1.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante1.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante2.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante2.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante2.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante2.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante3.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante3.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante3.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante3.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante4.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante4.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante4.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante4.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!jTextFieldEntradaNomeRestaurante5.getText().equals("") || !jTextFieldEntradaEnderecoRestaurante5.getText().equals("")){
            restaurante = new Restaurante();
            
            restaurante.setNome(jTextFieldEntradaNomeRestaurante5.getText());
            restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante5.getText());
            
            restaurantes.add(restaurante);
        }
        
        if(!restaurantes.isEmpty()){
            RoteiroDAO dao = new RoteiroDAO();
            
            if(dao.registrarRestaurante(Integer.parseInt(jLabelIdRoteiro.getText()), restaurantes)){
                JOptionPane.showMessageDialog(null, "Restaurante(s) criado(s) com sucesso!");
                
                new TelaCriarMaisPontosTuristicos(Integer.parseInt(jLabelIdRoteiro.getText())).setVisible(true);
            
                this.dispose();
            }
        }
        else{
            new TelaCriarMaisPontosTuristicos(Integer.parseInt(jLabelIdRoteiro.getText())).setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAdicionarPontoTuristicoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do restaurante?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaInicial().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do restaurante?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaCriarRoteiro().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jMenuItemExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do restaurante?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaExibirTodosRoteiros().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemExibirActionPerformed

    private void jMenuItemListaLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaLugaresActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do restaurante?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaContinentes().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemListaLugaresActionPerformed

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do restaurante?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarMaisRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarPontoTuristico;
    private javax.swing.JButton jButtonAdicionarRestaurante;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JLabel jLabelEnderecoRestaurante1;
    private javax.swing.JLabel jLabelEnderecoRestaurante2;
    private javax.swing.JLabel jLabelEnderecoRestaurante3;
    private javax.swing.JLabel jLabelEnderecoRestaurante4;
    private javax.swing.JLabel jLabelEnderecoRestaurante5;
    private javax.swing.JLabel jLabelGo;
    private javax.swing.JLabel jLabelGoImagem;
    private javax.swing.JLabel jLabelIdRoteiro;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelNomeRestaurante1;
    private javax.swing.JLabel jLabelNomeRestaurante2;
    private javax.swing.JLabel jLabelNomeRestaurante3;
    private javax.swing.JLabel jLabelNomeRestaurante4;
    private javax.swing.JLabel jLabelNomeRestaurante5;
    private javax.swing.JLabel jLabelRestaurante;
    private javax.swing.JLabel jLabelRoteiro;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemExibir;
    private javax.swing.JMenuItem jMenuItemListaLugares;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuRoteiro;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldEntradaEnderecoRestaurante1;
    private javax.swing.JTextField jTextFieldEntradaEnderecoRestaurante2;
    private javax.swing.JTextField jTextFieldEntradaEnderecoRestaurante3;
    private javax.swing.JTextField jTextFieldEntradaEnderecoRestaurante4;
    private javax.swing.JTextField jTextFieldEntradaEnderecoRestaurante5;
    private javax.swing.JTextField jTextFieldEntradaNomeRestaurante1;
    private javax.swing.JTextField jTextFieldEntradaNomeRestaurante2;
    private javax.swing.JTextField jTextFieldEntradaNomeRestaurante3;
    private javax.swing.JTextField jTextFieldEntradaNomeRestaurante4;
    private javax.swing.JTextField jTextFieldEntradaNomeRestaurante5;
    // End of variables declaration//GEN-END:variables
}
