package br.inatel.viagens.view;

import br.inatel.viagens.model.entities.Roteiro;
import br.inatel.viagens.model.entities.Transporte;
import br.inatel.viagens.model.entities.Hospedagem;
import br.inatel.viagens.model.entities.Restaurante;
import br.inatel.viagens.model.entities.PontoTuristico;
import br.inatel.viagens.model.dao.RoteiroDAO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Nathalya
 * 
 */

public class TelaCriarRoteiro extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaCriarRoteiro() {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelRoteiro = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jTextFieldEntradaDestino = new javax.swing.JTextField();
        jLabelDataIda = new javax.swing.JLabel();
        jFormattedTextFieldEntradaDataIda = new javax.swing.JFormattedTextField();
        jLabelDataVolta = new javax.swing.JLabel();
        jFormattedTextFieldEntradaDataVolta = new javax.swing.JFormattedTextField();
        jLabelTransporte = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelPrecoTransporte = new javax.swing.JLabel();
        jTextFieldEntradaPrecoTransporte = new javax.swing.JTextField();
        jLabelHorarioIda = new javax.swing.JLabel();
        jFormattedTextFieldEntradaHorarioIda = new javax.swing.JFormattedTextField();
        jLabelHorarioVolta = new javax.swing.JLabel();
        jFormattedTextFieldEntradaHorarioVolta = new javax.swing.JFormattedTextField();
        jLabelHospedagem = new javax.swing.JLabel();
        jLabelNomeHospedagem = new javax.swing.JLabel();
        jTextFieldEntradaNomeHospedagem = new javax.swing.JTextField();
        jLabelEnderecoHospedagem = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoHospedagem = new javax.swing.JTextField();
        jLabelCheckIn = new javax.swing.JLabel();
        jFormattedTextFieldEntradaCheckIn = new javax.swing.JFormattedTextField();
        jLabelCheckOut = new javax.swing.JLabel();
        jFormattedTextFieldEntradaCheckOut = new javax.swing.JFormattedTextField();
        jLabelPrecoHospedagem = new javax.swing.JLabel();
        jTextFieldEntradaPrecoHospedagem = new javax.swing.JTextField();
        jLabelRestaurante = new javax.swing.JLabel();
        jLabelNomeRestaurante = new javax.swing.JLabel();
        jTextFieldEntradaNomeRestaurante = new javax.swing.JTextField();
        jLabelEnderecoRestaurante = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoRestaurante = new javax.swing.JTextField();
        jLabelPontosTuristicos = new javax.swing.JLabel();
        jLabelNomePontoTuristico = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico = new javax.swing.JTextField();
        jLabelGo = new javax.swing.JLabel();
        jLabelGoImagem = new javax.swing.JLabel();
        jLabelPassaporte = new javax.swing.JLabel();
        jLabelAviao = new javax.swing.JLabel();
        jLabelHotel = new javax.swing.JLabel();
        jLabelComida = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jButtonAdicionarRestaurante = new javax.swing.JButton();
        jButtonAdicionarPontoTuristico = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuRoteiro = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemExibir = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemListaLugares = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Criar Roteiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabelRoteiro.setText("Roteiro");
        jFormattedText.add(jLabelRoteiro);
        jLabelRoteiro.setBounds(70, 0, 130, 60);

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelInfo.setText("Informações da Viagem:");
        jFormattedText.add(jLabelInfo);
        jLabelInfo.setBounds(60, 75, 230, 30);

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelDestino.setText("Destino:");
        jFormattedText.add(jLabelDestino);
        jLabelDestino.setBounds(20, 120, 50, 30);

        jTextFieldEntradaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaDestino);
        jTextFieldEntradaDestino.setBounds(80, 120, 310, 30);

        jLabelDataIda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelDataIda.setText("Data Ida:");
        jFormattedText.add(jLabelDataIda);
        jLabelDataIda.setBounds(20, 160, 60, 30);

        jFormattedTextFieldEntradaDataIda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        try {
            jFormattedTextFieldEntradaDataIda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedText.add(jFormattedTextFieldEntradaDataIda);
        jFormattedTextFieldEntradaDataIda.setBounds(80, 160, 90, 30);

        jLabelDataVolta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelDataVolta.setText("Data Volta:");
        jFormattedText.add(jLabelDataVolta);
        jLabelDataVolta.setBounds(230, 160, 70, 30);

        jFormattedTextFieldEntradaDataVolta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        try {
            jFormattedTextFieldEntradaDataVolta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedText.add(jFormattedTextFieldEntradaDataVolta);
        jFormattedTextFieldEntradaDataVolta.setBounds(300, 160, 90, 30);

        jLabelTransporte.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTransporte.setText("Transporte:");
        jFormattedText.add(jLabelTransporte);
        jLabelTransporte.setBounds(60, 200, 110, 30);

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelTipo.setText("Tipo:");
        jFormattedText.add(jLabelTipo);
        jLabelTipo.setBounds(20, 240, 30, 30);

        jLabelPrecoTransporte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoTransporte.setText("Preço:");
        jFormattedText.add(jLabelPrecoTransporte);
        jLabelPrecoTransporte.setBounds(20, 320, 50, 30);

        jTextFieldEntradaPrecoTransporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoTransporte);
        jTextFieldEntradaPrecoTransporte.setBounds(90, 320, 90, 30);

        jLabelHorarioIda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelHorarioIda.setText("Horário Ida:");
        jFormattedText.add(jLabelHorarioIda);
        jLabelHorarioIda.setBounds(20, 280, 80, 30);

        jFormattedTextFieldEntradaHorarioIda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        try {
            jFormattedTextFieldEntradaHorarioIda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedText.add(jFormattedTextFieldEntradaHorarioIda);
        jFormattedTextFieldEntradaHorarioIda.setBounds(90, 280, 90, 30);

        jLabelHorarioVolta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelHorarioVolta.setText("Horário Volta:");
        jFormattedText.add(jLabelHorarioVolta);
        jLabelHorarioVolta.setBounds(220, 280, 90, 30);

        jFormattedTextFieldEntradaHorarioVolta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        try {
            jFormattedTextFieldEntradaHorarioVolta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedText.add(jFormattedTextFieldEntradaHorarioVolta);
        jFormattedTextFieldEntradaHorarioVolta.setBounds(300, 280, 90, 30);

        jLabelHospedagem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelHospedagem.setText("Hospedagem:");
        jFormattedText.add(jLabelHospedagem);
        jLabelHospedagem.setBounds(60, 360, 140, 25);

        jLabelNomeHospedagem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomeHospedagem.setText("Nome:");
        jFormattedText.add(jLabelNomeHospedagem);
        jLabelNomeHospedagem.setBounds(20, 400, 50, 30);

        jTextFieldEntradaNomeHospedagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomeHospedagem);
        jTextFieldEntradaNomeHospedagem.setBounds(80, 400, 310, 30);

        jLabelEnderecoHospedagem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoHospedagem.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoHospedagem);
        jLabelEnderecoHospedagem.setBounds(20, 440, 80, 30);

        jTextFieldEntradaEnderecoHospedagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoHospedagem);
        jTextFieldEntradaEnderecoHospedagem.setBounds(80, 440, 310, 30);

        jLabelCheckIn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCheckIn.setText("Check In:");
        jFormattedText.add(jLabelCheckIn);
        jLabelCheckIn.setBounds(20, 480, 60, 30);

        jFormattedTextFieldEntradaCheckIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        try {
            jFormattedTextFieldEntradaCheckIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedText.add(jFormattedTextFieldEntradaCheckIn);
        jFormattedTextFieldEntradaCheckIn.setBounds(80, 480, 90, 30);

        jLabelCheckOut.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCheckOut.setText("Check Out:");
        jFormattedText.add(jLabelCheckOut);
        jLabelCheckOut.setBounds(230, 480, 70, 30);

        jFormattedTextFieldEntradaCheckOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        try {
            jFormattedTextFieldEntradaCheckOut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedText.add(jFormattedTextFieldEntradaCheckOut);
        jFormattedTextFieldEntradaCheckOut.setBounds(300, 480, 90, 30);

        jLabelPrecoHospedagem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoHospedagem.setText("Preço:");
        jFormattedText.add(jLabelPrecoHospedagem);
        jLabelPrecoHospedagem.setBounds(20, 520, 60, 30);

        jTextFieldEntradaPrecoHospedagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoHospedagem);
        jTextFieldEntradaPrecoHospedagem.setBounds(80, 520, 90, 30);

        jLabelRestaurante.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelRestaurante.setText("Restaurante:");
        jFormattedText.add(jLabelRestaurante);
        jLabelRestaurante.setBounds(600, 80, 130, 25);

        jLabelNomeRestaurante.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomeRestaurante.setText("Nome:");
        jFormattedText.add(jLabelNomeRestaurante);
        jLabelNomeRestaurante.setBounds(560, 120, 50, 30);

        jTextFieldEntradaNomeRestaurante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomeRestaurante);
        jTextFieldEntradaNomeRestaurante.setBounds(620, 120, 310, 30);

        jLabelEnderecoRestaurante.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoRestaurante.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoRestaurante);
        jLabelEnderecoRestaurante.setBounds(560, 160, 60, 30);

        jTextFieldEntradaEnderecoRestaurante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoRestaurante);
        jTextFieldEntradaEnderecoRestaurante.setBounds(620, 160, 310, 30);

        jLabelPontosTuristicos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPontosTuristicos.setText("Pontos Turísticos:");
        jFormattedText.add(jLabelPontosTuristicos);
        jLabelPontosTuristicos.setBounds(600, 250, 170, 25);

        jLabelNomePontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico);
        jLabelNomePontoTuristico.setBounds(560, 290, 50, 30);

        jTextFieldEntradaNomePontoTuristico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico);
        jTextFieldEntradaNomePontoTuristico.setBounds(620, 290, 310, 30);

        jLabelPrecoPontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico);
        jLabelPrecoPontoTuristico.setBounds(560, 370, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico);
        jTextFieldEntradaPrecoPontoTuristico.setBounds(620, 370, 90, 30);

        jLabelEnderecoPontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico);
        jLabelEnderecoPontoTuristico.setBounds(560, 330, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico);
        jTextFieldEntradaEnderecoPontoTuristico.setBounds(620, 330, 310, 30);

        jLabelGo.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelGo.setText("GO!");
        jLabelGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGo);
        jLabelGo.setBounds(870, 550, 50, 40);

        jLabelGoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\plane.png")); // NOI18N
        jLabelGoImagem.setText("jLabel1");
        jLabelGoImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoImagemMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGoImagem);
        jLabelGoImagem.setBounds(740, 400, 260, 190);

        jLabelPassaporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\passport.png")); // NOI18N
        jFormattedText.add(jLabelPassaporte);
        jLabelPassaporte.setBounds(20, 70, 50, 40);

        jLabelAviao.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\transportation.png")); // NOI18N
        jFormattedText.add(jLabelAviao);
        jLabelAviao.setBounds(20, 200, 30, 30);

        jLabelHotel.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\hotel.png")); // NOI18N
        jFormattedText.add(jLabelHotel);
        jLabelHotel.setBounds(20, 350, 30, 40);

        jLabelComida.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\localization.png")); // NOI18N
        jFormattedText.add(jLabelComida);
        jLabelComida.setBounds(560, 230, 30, 60);

        jLabelLocal.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\restaurant.png")); // NOI18N
        jFormattedText.add(jLabelLocal);
        jLabelLocal.setBounds(560, 80, 30, 30);

        jButtonAdicionarRestaurante.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarRestaurante.setText(" Restaurantes");
        jButtonAdicionarRestaurante.setBorder(null);
        jButtonAdicionarRestaurante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarRestauranteActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarRestaurante);
        jButtonAdicionarRestaurante.setBounds(560, 200, 150, 30);

        jButtonAdicionarPontoTuristico.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarPontoTuristico.setText("  Pontos Turísticos");
        jButtonAdicionarPontoTuristico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarPontoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPontoTuristicoActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarPontoTuristico);
        jButtonAdicionarPontoTuristico.setBounds(560, 410, 150, 30);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonVoltar);
        jButtonVoltar.setBounds(840, 20, 90, 30);

        jComboBoxTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jComboBoxTipo);
        jComboBoxTipo.setBounds(90, 240, 90, 30);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuRoteiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\script.png")); // NOI18N
        jMenuRoteiro.setText("Roteiro");

        jMenuItemCriar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemCriar);

        jMenuItemExibir.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jMenuItemExibir.setText("Exibir");
        jMenuItemExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemExibir);

        jMenuBar.add(jMenuRoteiro);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");

        jMenuItemListaLugares.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\list.png")); // NOI18N
        jMenuItemListaLugares.setText("Lista de Lugares");
        jMenuItemListaLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaLugaresActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItemListaLugares);

        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoMouseClicked
        Roteiro roteiro = new Roteiro();
        roteiro.setDestino(jTextFieldEntradaDestino.getText());
        roteiro.setDataIda(jFormattedTextFieldEntradaDataIda.getText());
        roteiro.setDataVolta(jFormattedTextFieldEntradaDataVolta.getText());
        
        Transporte transporte = new Transporte();
        transporte.setTipo(String.valueOf(jComboBoxTipo.getSelectedIndex()));
        transporte.setHorarioIda(jFormattedTextFieldEntradaHorarioIda.getText());
        transporte.setHorarioVolta(jFormattedTextFieldEntradaHorarioVolta.getText());
        transporte.setPreco(jTextFieldEntradaPrecoTransporte.getText());

        Hospedagem hospedagem = new Hospedagem();
        hospedagem.setNome(jTextFieldEntradaNomeHospedagem.getText());
        hospedagem.setEndereco(jTextFieldEntradaEnderecoHospedagem.getText());
        hospedagem.setCheckIn(jFormattedTextFieldEntradaCheckIn.getText());
        hospedagem.setCheckOut(jFormattedTextFieldEntradaCheckOut.getText());
        hospedagem.setPreco(jTextFieldEntradaPrecoHospedagem.getText());

        Restaurante restaurante = new Restaurante();
        restaurante.setNome(jTextFieldEntradaNomeRestaurante.getText());
        restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante.getText());

        PontoTuristico pontoTuristico = new PontoTuristico();
        pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico.getText());
        pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico.getText());
        pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico.getText());

        RoteiroDAO dao = new RoteiroDAO();
        if(dao.registrarRoteiro(roteiro, transporte, hospedagem, restaurante, pontoTuristico)){
            JOptionPane.showMessageDialog(null, "Roteiro criado com sucesso!");
            
            new TelaInicial().setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jLabelGoMouseClicked

    private void jLabelGoImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoImagemMouseClicked
        jLabelGoMouseClicked(evt);
    }//GEN-LAST:event_jLabelGoImagemMouseClicked

    private void jButtonAdicionarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarRestauranteActionPerformed
        Roteiro roteiro = new Roteiro();
        roteiro.setDestino(jTextFieldEntradaDestino.getText());
        roteiro.setDataIda(jFormattedTextFieldEntradaDataIda.getText());
        roteiro.setDataVolta(jFormattedTextFieldEntradaDataVolta.getText());

        Transporte transporte = new Transporte();
        transporte.setTipo(String.valueOf(jComboBoxTipo.getSelectedIndex()));
        transporte.setHorarioIda(jFormattedTextFieldEntradaHorarioIda.getText());
        transporte.setHorarioVolta(jFormattedTextFieldEntradaHorarioVolta.getText());
        transporte.setPreco(jTextFieldEntradaPrecoTransporte.getText());

        Hospedagem hospedagem = new Hospedagem();
        hospedagem.setNome(jTextFieldEntradaNomeHospedagem.getText());
        hospedagem.setEndereco(jTextFieldEntradaEnderecoHospedagem.getText());
        hospedagem.setCheckIn(jFormattedTextFieldEntradaCheckIn.getText());
        hospedagem.setCheckOut(jFormattedTextFieldEntradaCheckOut.getText());
        hospedagem.setPreco(jTextFieldEntradaPrecoHospedagem.getText());

        Restaurante restaurante = new Restaurante();
        restaurante.setNome(jTextFieldEntradaNomeRestaurante.getText());
        restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante.getText());

        PontoTuristico pontoTuristico = new PontoTuristico();
        pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico.getText());
        pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico.getText());
        pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico.getText());

        RoteiroDAO dao = new RoteiroDAO();
        if(dao.registrarRoteiro(roteiro, transporte, hospedagem, restaurante, pontoTuristico)){
            JOptionPane.showMessageDialog(null, "Roteiro criado com sucesso!");
            
            new TelaCriarMaisRestaurantes(-1).setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAdicionarRestauranteActionPerformed

    private void jMenuItemExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do roteiro?", "Voltar", 0);
        
        if(i == 0){ //Escolheu "Sim"
            new TelaExibirTodosRoteiros().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemExibirActionPerformed

    private void jButtonAdicionarPontoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPontoTuristicoActionPerformed
        Roteiro roteiro = new Roteiro();
        roteiro.setDestino(jTextFieldEntradaDestino.getText());
        roteiro.setDataIda(jFormattedTextFieldEntradaDataIda.getText());
        roteiro.setDataVolta(jFormattedTextFieldEntradaDataVolta.getText());

        Transporte transporte = new Transporte();
        transporte.setTipo(String.valueOf(jComboBoxTipo.getSelectedIndex()));
        transporte.setHorarioIda(jFormattedTextFieldEntradaHorarioIda.getText());
        transporte.setHorarioVolta(jFormattedTextFieldEntradaHorarioVolta.getText());
        transporte.setPreco(jTextFieldEntradaPrecoTransporte.getText());

        Hospedagem hospedagem = new Hospedagem();
        hospedagem.setNome(jTextFieldEntradaNomeHospedagem.getText());
        hospedagem.setEndereco(jTextFieldEntradaEnderecoHospedagem.getText());
        hospedagem.setCheckIn(jFormattedTextFieldEntradaCheckIn.getText());
        hospedagem.setCheckOut(jFormattedTextFieldEntradaCheckOut.getText());
        hospedagem.setPreco(jTextFieldEntradaPrecoHospedagem.getText());

        Restaurante restaurante = new Restaurante();
        restaurante.setNome(jTextFieldEntradaNomeRestaurante.getText());
        restaurante.setEndereco(jTextFieldEntradaEnderecoRestaurante.getText());

        PontoTuristico pontoTuristico = new PontoTuristico();
        pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico.getText());
        pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico.getText());
        pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico.getText());

        RoteiroDAO dao = new RoteiroDAO();
        if(dao.registrarRoteiro(roteiro, transporte, hospedagem, restaurante, pontoTuristico)){
            JOptionPane.showMessageDialog(null, "Roteiro criado com sucesso!");
            
            new TelaCriarMaisPontosTuristicos(-1).setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAdicionarPontoTuristicoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do roteiro?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaInicial().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        RoteiroDAO dao = new RoteiroDAO();
        
        dao.inserirTipoTransporte(jComboBoxTipo);
        
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do roteiro?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaCriarRoteiro().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jMenuItemListaLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaLugaresActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do roteiro?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaContinentes().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemListaLugaresActionPerformed

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do roteiro?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarRoteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarRoteiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarPontoTuristico;
    private javax.swing.JButton jButtonAdicionarRestaurante;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JFormattedTextField jFormattedTextFieldEntradaCheckIn;
    private javax.swing.JFormattedTextField jFormattedTextFieldEntradaCheckOut;
    private javax.swing.JFormattedTextField jFormattedTextFieldEntradaDataIda;
    private javax.swing.JFormattedTextField jFormattedTextFieldEntradaDataVolta;
    private javax.swing.JFormattedTextField jFormattedTextFieldEntradaHorarioIda;
    private javax.swing.JFormattedTextField jFormattedTextFieldEntradaHorarioVolta;
    private javax.swing.JLabel jLabelAviao;
    private javax.swing.JLabel jLabelCheckIn;
    private javax.swing.JLabel jLabelCheckOut;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelDataIda;
    private javax.swing.JLabel jLabelDataVolta;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelEnderecoHospedagem;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico;
    private javax.swing.JLabel jLabelEnderecoRestaurante;
    private javax.swing.JLabel jLabelGo;
    private javax.swing.JLabel jLabelGoImagem;
    private javax.swing.JLabel jLabelHorarioIda;
    private javax.swing.JLabel jLabelHorarioVolta;
    private javax.swing.JLabel jLabelHospedagem;
    private javax.swing.JLabel jLabelHotel;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelNomeHospedagem;
    private javax.swing.JLabel jLabelNomePontoTuristico;
    private javax.swing.JLabel jLabelNomeRestaurante;
    private javax.swing.JLabel jLabelPassaporte;
    private javax.swing.JLabel jLabelPontosTuristicos;
    private javax.swing.JLabel jLabelPrecoHospedagem;
    private javax.swing.JLabel jLabelPrecoPontoTuristico;
    private javax.swing.JLabel jLabelPrecoTransporte;
    private javax.swing.JLabel jLabelRestaurante;
    private javax.swing.JLabel jLabelRoteiro;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTransporte;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemExibir;
    private javax.swing.JMenuItem jMenuItemListaLugares;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuRoteiro;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JTextField jTextFieldEntradaDestino;
    private javax.swing.JTextField jTextFieldEntradaEnderecoHospedagem;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico;
    private javax.swing.JTextField jTextFieldEntradaEnderecoRestaurante;
    private javax.swing.JTextField jTextFieldEntradaNomeHospedagem;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico;
    private javax.swing.JTextField jTextFieldEntradaNomeRestaurante;
    private javax.swing.JTextField jTextFieldEntradaPrecoHospedagem;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico;
    private javax.swing.JTextField jTextFieldEntradaPrecoTransporte;
    // End of variables declaration//GEN-END:variables
}
