package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.RoteiroDAO;
import br.inatel.viagens.model.entities.PontoTuristico;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Nathalya
 * 
 */

public class TelaCriarMaisPontosTuristicos extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaCriarMaisPontosTuristicos(int id) {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
        
        jLabelIdRoteiro.setText(String.valueOf(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelRoteiro = new javax.swing.JLabel();
        jLabelPontosTuristicos = new javax.swing.JLabel();
        jLabelNomePontoTuristico1 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico1 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico1 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico1 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico1 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico1 = new javax.swing.JTextField();
        jLabelGo = new javax.swing.JLabel();
        jLabelGoImagem = new javax.swing.JLabel();
        jLabelComida = new javax.swing.JLabel();
        jButtonAdicionarRestaurante = new javax.swing.JButton();
        jButtonAdicionarPontoTuristico = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNomePontoTuristico2 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico2 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico2 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico2 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico2 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelNomePontoTuristico3 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico3 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico3 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico3 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico3 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico3 = new javax.swing.JTextField();
        jLabelNomePontoTuristico4 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico4 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico4 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico4 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico4 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico4 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelNomePontoTuristico5 = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico5 = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico5 = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico5 = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico5 = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico5 = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jLabelIdRoteiro = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuRoteiro = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemExibir = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemListaLugares = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Pontos Turísticos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabelRoteiro.setText("Roteiro");
        jFormattedText.add(jLabelRoteiro);
        jLabelRoteiro.setBounds(70, 0, 130, 60);

        jLabelPontosTuristicos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPontosTuristicos.setText("Pontos Turísticos:");
        jFormattedText.add(jLabelPontosTuristicos);
        jLabelPontosTuristicos.setBounds(60, 80, 170, 25);

        jLabelNomePontoTuristico1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico1.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico1);
        jLabelNomePontoTuristico1.setBounds(20, 120, 50, 30);

        jTextFieldEntradaNomePontoTuristico1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico1);
        jTextFieldEntradaNomePontoTuristico1.setBounds(80, 120, 310, 30);

        jLabelEnderecoPontoTuristico1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico1.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico1);
        jLabelEnderecoPontoTuristico1.setBounds(20, 160, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico1);
        jTextFieldEntradaEnderecoPontoTuristico1.setBounds(80, 160, 310, 30);

        jLabelPrecoPontoTuristico1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico1.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico1);
        jLabelPrecoPontoTuristico1.setBounds(20, 200, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico1);
        jTextFieldEntradaPrecoPontoTuristico1.setBounds(80, 200, 90, 30);

        jLabelGo.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelGo.setText("GO!");
        jLabelGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGo);
        jLabelGo.setBounds(870, 550, 50, 40);

        jLabelGoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\plane.png")); // NOI18N
        jLabelGoImagem.setText("jLabel1");
        jLabelGoImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoImagemMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGoImagem);
        jLabelGoImagem.setBounds(740, 400, 260, 190);

        jLabelComida.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\localization.png")); // NOI18N
        jFormattedText.add(jLabelComida);
        jLabelComida.setBounds(20, 60, 30, 60);

        jButtonAdicionarRestaurante.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarRestaurante.setText("Restaurantes");
        jButtonAdicionarRestaurante.setBorder(null);
        jButtonAdicionarRestaurante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarRestauranteActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarRestaurante);
        jButtonAdicionarRestaurante.setBounds(560, 460, 150, 30);

        jButtonAdicionarPontoTuristico.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarPontoTuristico.setText(" Pontos Turísticos");
        jButtonAdicionarPontoTuristico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarPontoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPontoTuristicoActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarPontoTuristico);
        jButtonAdicionarPontoTuristico.setBounds(560, 420, 150, 30);
        jFormattedText.add(jSeparator1);
        jSeparator1.setBounds(20, 260, 370, 10);

        jLabelNomePontoTuristico2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico2.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico2);
        jLabelNomePontoTuristico2.setBounds(20, 290, 50, 30);

        jTextFieldEntradaNomePontoTuristico2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico2);
        jTextFieldEntradaNomePontoTuristico2.setBounds(80, 290, 310, 30);

        jLabelEnderecoPontoTuristico2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico2.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico2);
        jLabelEnderecoPontoTuristico2.setBounds(20, 330, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico2);
        jTextFieldEntradaEnderecoPontoTuristico2.setBounds(80, 330, 310, 30);

        jLabelPrecoPontoTuristico2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico2.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico2);
        jLabelPrecoPontoTuristico2.setBounds(20, 370, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico2);
        jTextFieldEntradaPrecoPontoTuristico2.setBounds(80, 370, 90, 30);
        jFormattedText.add(jSeparator2);
        jSeparator2.setBounds(20, 430, 370, 10);

        jLabelNomePontoTuristico3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico3.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico3);
        jLabelNomePontoTuristico3.setBounds(20, 460, 50, 30);

        jTextFieldEntradaNomePontoTuristico3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico3);
        jTextFieldEntradaNomePontoTuristico3.setBounds(80, 460, 310, 30);

        jLabelEnderecoPontoTuristico3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico3.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico3);
        jLabelEnderecoPontoTuristico3.setBounds(20, 500, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico3);
        jTextFieldEntradaEnderecoPontoTuristico3.setBounds(80, 500, 310, 30);

        jLabelPrecoPontoTuristico3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico3.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico3);
        jLabelPrecoPontoTuristico3.setBounds(20, 540, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico3);
        jTextFieldEntradaPrecoPontoTuristico3.setBounds(80, 540, 90, 30);

        jLabelNomePontoTuristico4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico4.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico4);
        jLabelNomePontoTuristico4.setBounds(560, 120, 50, 30);

        jTextFieldEntradaNomePontoTuristico4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico4);
        jTextFieldEntradaNomePontoTuristico4.setBounds(620, 120, 310, 30);

        jLabelEnderecoPontoTuristico4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico4.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico4);
        jLabelEnderecoPontoTuristico4.setBounds(560, 160, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico4);
        jTextFieldEntradaEnderecoPontoTuristico4.setBounds(620, 160, 310, 30);

        jLabelPrecoPontoTuristico4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico4.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico4);
        jLabelPrecoPontoTuristico4.setBounds(560, 200, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico4);
        jTextFieldEntradaPrecoPontoTuristico4.setBounds(620, 200, 90, 30);
        jFormattedText.add(jSeparator3);
        jSeparator3.setBounds(560, 250, 370, 10);

        jLabelNomePontoTuristico5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico5.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico5);
        jLabelNomePontoTuristico5.setBounds(560, 280, 50, 30);

        jTextFieldEntradaNomePontoTuristico5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico5);
        jTextFieldEntradaNomePontoTuristico5.setBounds(620, 280, 310, 30);

        jLabelEnderecoPontoTuristico5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico5.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico5);
        jLabelEnderecoPontoTuristico5.setBounds(560, 320, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico5);
        jTextFieldEntradaEnderecoPontoTuristico5.setBounds(620, 320, 310, 30);

        jLabelPrecoPontoTuristico5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico5.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico5);
        jLabelPrecoPontoTuristico5.setBounds(560, 360, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico5);
        jTextFieldEntradaPrecoPontoTuristico5.setBounds(620, 360, 90, 30);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonVoltar);
        jButtonVoltar.setBounds(840, 20, 90, 30);
        jFormattedText.add(jLabelIdRoteiro);
        jLabelIdRoteiro.setBounds(210, 30, 0, 0);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuRoteiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\script.png")); // NOI18N
        jMenuRoteiro.setText("Roteiro");

        jMenuItemCriar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemCriar);

        jMenuItemExibir.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jMenuItemExibir.setText("Exibir");
        jMenuItemExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemExibir);

        jMenuBar.add(jMenuRoteiro);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");

        jMenuItemListaLugares.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\list.png")); // NOI18N
        jMenuItemListaLugares.setText("Lista de Lugares");
        jMenuItemListaLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaLugaresActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItemListaLugares);

        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoMouseClicked
        PontoTuristico pontoTuristico = new PontoTuristico();
        
        List<PontoTuristico> pontosTuristicos = new ArrayList<>();
        
        if(!jTextFieldEntradaNomePontoTuristico1.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico1.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico1.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico1.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico1.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico1.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico2.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico2.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico2.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico2.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico2.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico2.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico3.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico3.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico3.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico3.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico3.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico3.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico4.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico4.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico4.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico4.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico4.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico4.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico5.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico5.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico5.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico5.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico5.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico5.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!pontosTuristicos.isEmpty()){
            RoteiroDAO dao = new RoteiroDAO();
            
            if(dao.registrarPontoTuristico(Integer.parseInt(jLabelIdRoteiro.getText()), pontosTuristicos)){
                JOptionPane.showMessageDialog(null, "Ponto(s) turístico(s) criado(s) com sucesso!");
                
                new TelaInicial().setVisible(true);
            
                this.dispose();
            }
        }
        else{
            new TelaInicial().setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jLabelGoMouseClicked

    private void jLabelGoImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoImagemMouseClicked
        jLabelGoMouseClicked(evt);
    }//GEN-LAST:event_jLabelGoImagemMouseClicked

    private void jButtonAdicionarPontoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPontoTuristicoActionPerformed
        PontoTuristico pontoTuristico = new PontoTuristico();
        
        List<PontoTuristico> pontosTuristicos = new ArrayList<>();
        
        if(!jTextFieldEntradaNomePontoTuristico1.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico1.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico1.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico1.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico1.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico1.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico2.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico2.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico2.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico2.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico2.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico2.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico3.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico3.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico3.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico3.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico3.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico3.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico4.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico4.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico4.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico4.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico4.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico4.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico5.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico5.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico5.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico5.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico5.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico5.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(pontosTuristicos.size() == 5){
            RoteiroDAO dao = new RoteiroDAO();
            
            if(dao.registrarPontoTuristico(Integer.parseInt(jLabelIdRoteiro.getText()), pontosTuristicos)){
                JOptionPane.showMessageDialog(null, "Ponto(s) turístico(s) criado(s) com sucesso!");
                
                new TelaCriarMaisPontosTuristicos(Integer.parseInt(jLabelIdRoteiro.getText())).setVisible(true);

                this.dispose();
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
    }//GEN-LAST:event_jButtonAdicionarPontoTuristicoActionPerformed

    private void jButtonAdicionarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarRestauranteActionPerformed
        PontoTuristico pontoTuristico = new PontoTuristico();
        
        List<PontoTuristico> pontosTuristicos = new ArrayList<>();
        
        if(!jTextFieldEntradaNomePontoTuristico1.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico1.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico1.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico1.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico1.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico1.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico2.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico2.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico2.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico2.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico2.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico2.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico3.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico3.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico3.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico3.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico3.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico3.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico4.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico4.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico4.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico4.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico4.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico4.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!jTextFieldEntradaNomePontoTuristico5.getText().equals("") || !jTextFieldEntradaEnderecoPontoTuristico5.getText().equals("") || ! jTextFieldEntradaPrecoPontoTuristico5.getText().equals("")){
            pontoTuristico = new PontoTuristico();
            
            pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico5.getText());
            pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico5.getText());
            pontoTuristico.setPreco(jTextFieldEntradaPrecoPontoTuristico5.getText());
            
            pontosTuristicos.add(pontoTuristico);
        }
        
        if(!pontosTuristicos.isEmpty()){
            RoteiroDAO dao = new RoteiroDAO();
            
            if(dao.registrarPontoTuristico(Integer.parseInt(jLabelIdRoteiro.getText()), pontosTuristicos)){
                JOptionPane.showMessageDialog(null, "Ponto(s) turístico(s) criado(s) com sucesso!");
                
                new TelaCriarMaisRestaurantes(Integer.parseInt(jLabelIdRoteiro.getText())).setVisible(true);
            
                this.dispose();
            }
        }
        else{
            new TelaCriarMaisRestaurantes(Integer.parseInt(jLabelIdRoteiro.getText())).setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAdicionarRestauranteActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do ponto turístico?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaInicial().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do ponto turístico?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaCriarRoteiro().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jMenuItemExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do ponto turístico?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaExibirTodosRoteiros().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemExibirActionPerformed

    private void jMenuItemListaLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaLugaresActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do ponto turístico?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaContinentes().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItemListaLugaresActionPerformed

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações do ponto turístico?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PontoTuristico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PontoTuristico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PontoTuristico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PontoTuristico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarPontoTuristico;
    private javax.swing.JButton jButtonAdicionarRestaurante;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico1;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico2;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico3;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico4;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico5;
    private javax.swing.JLabel jLabelGo;
    private javax.swing.JLabel jLabelGoImagem;
    private javax.swing.JLabel jLabelIdRoteiro;
    private javax.swing.JLabel jLabelNomePontoTuristico1;
    private javax.swing.JLabel jLabelNomePontoTuristico2;
    private javax.swing.JLabel jLabelNomePontoTuristico3;
    private javax.swing.JLabel jLabelNomePontoTuristico4;
    private javax.swing.JLabel jLabelNomePontoTuristico5;
    private javax.swing.JLabel jLabelPontosTuristicos;
    private javax.swing.JLabel jLabelPrecoPontoTuristico1;
    private javax.swing.JLabel jLabelPrecoPontoTuristico2;
    private javax.swing.JLabel jLabelPrecoPontoTuristico3;
    private javax.swing.JLabel jLabelPrecoPontoTuristico4;
    private javax.swing.JLabel jLabelPrecoPontoTuristico5;
    private javax.swing.JLabel jLabelRoteiro;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemExibir;
    private javax.swing.JMenuItem jMenuItemListaLugares;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuRoteiro;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico1;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico2;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico3;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico4;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico5;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico1;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico2;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico3;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico4;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico5;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico1;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico2;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico3;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico4;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico5;
    // End of variables declaration//GEN-END:variables
}
