package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.LugaresDAO;
import br.inatel.viagens.model.entities.Lugares;
import br.inatel.viagens.model.entities.PontoTuristicoLugares;
import br.inatel.viagens.model.entities.Viagens;
import br.inatel.viagens.util.ConverterTipos;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Nathalya
 * 
 */

public class TelaEditarLugaresAdmin extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaEditarLugaresAdmin(String id, String destino) {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
        
        jLabelIdDestino.setText(id);
        jLabelDestinoViagem.setText(destino);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelRoteiro = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jTextFieldEntradaDestino = new javax.swing.JTextField();
        jLabelPontosTuristicos = new javax.swing.JLabel();
        jLabelGo = new javax.swing.JLabel();
        jLabelGoImagem = new javax.swing.JLabel();
        jLabelPassaporte = new javax.swing.JLabel();
        jLabelComida = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelAltaTemporada = new javax.swing.JLabel();
        jScrollPaneAltaTemporada = new javax.swing.JScrollPane();
        jTextAreaAltaTemporada = new javax.swing.JTextArea();
        jLabelClima = new javax.swing.JLabel();
        jScrollPaneClima = new javax.swing.JScrollPane();
        jTextAreaClima = new javax.swing.JTextArea();
        jLabelContinente = new javax.swing.JLabel();
        jComboBoxContinente = new javax.swing.JComboBox<>();
        jLabelIdDestino = new javax.swing.JLabel();
        jLabelDestinoViagem = new javax.swing.JLabel();
        jPanelPontoTuristico = new javax.swing.JPanel();
        jScrollPanePontoTuristico = new javax.swing.JScrollPane();
        jTablePontoTuristico = new javax.swing.JTable();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuViagem = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Criar Roteiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabelRoteiro.setText("Para onde Viajar?");
        jFormattedText.add(jLabelRoteiro);
        jLabelRoteiro.setBounds(70, 0, 300, 60);

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelInfo.setText("Informações da Viagem:");
        jFormattedText.add(jLabelInfo);
        jLabelInfo.setBounds(60, 75, 230, 30);

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelDestino.setText("Destino:");
        jFormattedText.add(jLabelDestino);
        jLabelDestino.setBounds(20, 170, 50, 30);

        jTextFieldEntradaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaDestino);
        jTextFieldEntradaDestino.setBounds(120, 170, 260, 30);

        jLabelPontosTuristicos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPontosTuristicos.setText("Pontos Turísticos:");
        jFormattedText.add(jLabelPontosTuristicos);
        jLabelPontosTuristicos.setBounds(440, 80, 170, 25);

        jLabelGo.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelGo.setText("GO!");
        jLabelGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGo);
        jLabelGo.setBounds(870, 550, 50, 40);

        jLabelGoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\plane.png")); // NOI18N
        jLabelGoImagem.setText("jLabel1");
        jLabelGoImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoImagemMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGoImagem);
        jLabelGoImagem.setBounds(740, 400, 260, 190);

        jLabelPassaporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\passport.png")); // NOI18N
        jFormattedText.add(jLabelPassaporte);
        jLabelPassaporte.setBounds(20, 70, 50, 40);

        jLabelComida.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\localization.png")); // NOI18N
        jFormattedText.add(jLabelComida);
        jLabelComida.setBounds(400, 60, 30, 60);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonVoltar);
        jButtonVoltar.setBounds(840, 20, 90, 30);

        jLabelAltaTemporada.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelAltaTemporada.setText("Alta Temporada:");
        jFormattedText.add(jLabelAltaTemporada);
        jLabelAltaTemporada.setBounds(20, 210, 110, 16);

        jTextAreaAltaTemporada.setColumns(20);
        jTextAreaAltaTemporada.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaAltaTemporada.setRows(5);
        jTextAreaAltaTemporada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jScrollPaneAltaTemporada.setViewportView(jTextAreaAltaTemporada);

        jFormattedText.add(jScrollPaneAltaTemporada);
        jScrollPaneAltaTemporada.setBounds(120, 210, 260, 140);

        jLabelClima.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelClima.setText("Clima:");
        jFormattedText.add(jLabelClima);
        jLabelClima.setBounds(20, 366, 50, 20);

        jTextAreaClima.setColumns(20);
        jTextAreaClima.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaClima.setRows(5);
        jTextAreaClima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jScrollPaneClima.setViewportView(jTextAreaClima);

        jFormattedText.add(jScrollPaneClima);
        jScrollPaneClima.setBounds(120, 360, 260, 140);

        jLabelContinente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelContinente.setText("Continente:");
        jFormattedText.add(jLabelContinente);
        jLabelContinente.setBounds(20, 130, 90, 30);

        jComboBoxContinente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "América do Norte", "América do Sul", "Europa", "África", "Oceania", "Ásia" }));
        jFormattedText.add(jComboBoxContinente);
        jComboBoxContinente.setBounds(120, 130, 260, 30);
        jFormattedText.add(jLabelIdDestino);
        jLabelIdDestino.setBounds(420, 60, 0, 0);
        jFormattedText.add(jLabelDestinoViagem);
        jLabelDestinoViagem.setBounds(470, 40, 0, 0);

        jTablePontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTablePontoTuristico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço", "Preço", "Latitude", "Longitude"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePontoTuristico.setRowHeight(30);
        jTablePontoTuristico.setSelectionBackground(new java.awt.Color(74, 39, 72));
        jTablePontoTuristico.getTableHeader().setReorderingAllowed(false);
        jScrollPanePontoTuristico.setViewportView(jTablePontoTuristico);

        javax.swing.GroupLayout jPanelPontoTuristicoLayout = new javax.swing.GroupLayout(jPanelPontoTuristico);
        jPanelPontoTuristico.setLayout(jPanelPontoTuristicoLayout);
        jPanelPontoTuristicoLayout.setHorizontalGroup(
            jPanelPontoTuristicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePontoTuristico, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanelPontoTuristicoLayout.setVerticalGroup(
            jPanelPontoTuristicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPontoTuristicoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPanePontoTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jFormattedText.add(jPanelPontoTuristico);
        jPanelPontoTuristico.setBounds(410, 130, 550, 250);

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionar);
        jButtonAdicionar.setBounds(610, 80, 30, 30);

        jButtonDeletar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\delete.png")); // NOI18N
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonDeletar);
        jButtonDeletar.setBounds(650, 80, 30, 30);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");
        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoMouseClicked
        int continente = jComboBoxContinente.getSelectedIndex() + 1;
        
        Lugares lugar = new Lugares("", "");
        
        lugar.setDestino(jTextFieldEntradaDestino.getText());
        
        Viagens viagem = new Viagens();
        
        jTextAreaAltaTemporada.setLineWrap(true);
        jTextAreaClima.setLineWrap(true);
        
        viagem.setAltaTemporada(jTextAreaAltaTemporada.getText());
        viagem.setClima(jTextAreaClima.getText());
        
        LugaresDAO dao = new LugaresDAO();
        
        boolean alteracaoViagem = true;
        
        if(!dao.editarViagem(continente, lugar, viagem, Integer.parseInt(jLabelIdDestino.getText()))){
            alteracaoViagem = false;
        }
        
        int linhasPontoTuristico = jTablePontoTuristico.getRowCount();
        
        PontoTuristicoLugares pontoTuristico = new PontoTuristicoLugares();
        
        boolean alteracaoPontoTuristico = true;
        
        for(int i = 0; i < linhasPontoTuristico; i++){
            pontoTuristico.setId(Integer.parseInt(String.valueOf(jTablePontoTuristico.getValueAt(i, 0))));
            pontoTuristico.setNome(String.valueOf(jTablePontoTuristico.getValueAt(i, 1)));
            pontoTuristico.setEndereco(String.valueOf(jTablePontoTuristico.getValueAt(i, 2)));
            pontoTuristico.setPreco(Double.parseDouble(String.valueOf(jTablePontoTuristico.getValueAt(i, 3))));
            PontoTuristicoLugares.latitude = Double.parseDouble(String.valueOf(jTablePontoTuristico.getValueAt(i, 4)).replace(",", "."));
            PontoTuristicoLugares.longitude = Double.parseDouble(String.valueOf(jTablePontoTuristico.getValueAt(i, 5)).replace(",", "."));
            
            if(!dao.editarPontoTuristico(pontoTuristico)){
                alteracaoPontoTuristico = false;
            }
        }
        
        if(alteracaoViagem && alteracaoPontoTuristico){
            new TelaListaLugaresAdmin().setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro ao atualizar os dados!");
        }
    }//GEN-LAST:event_jLabelGoMouseClicked

    private void jLabelGoImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoImagemMouseClicked
        jLabelGoMouseClicked(evt);
    }//GEN-LAST:event_jLabelGoImagemMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja voltar sem salvar as alterações?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaListaLugaresAdmin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int id = Integer.valueOf(jLabelIdDestino.getText());
        String destino = jLabelDestinoViagem.getText();
        
        jTextAreaAltaTemporada.setLineWrap(true);
        jTextAreaClima.setLineWrap(true);
        
        LugaresDAO dao = new LugaresDAO();
        
        Viagens viagem = new Viagens();
        
        viagem = dao.buscarViagem(id);
        
        jTextFieldEntradaDestino.setText(destino);
        jTextAreaAltaTemporada.setText(viagem.getAltaTemporada());
        jTextAreaClima.setText(viagem.getClima());
        
        jTablePontoTuristico.setModel(dao.buscarPontoTuristico(id));
        
        jTablePontoTuristico.getColumnModel().getColumn(0).setMinWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(0).setMaxWidth(0);
        jTablePontoTuristico.getColumnModel().getColumn(0).setWidth(0);
        
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaListaLugaresAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        new TelaCriarMaisPontosTuristicosViagem(-1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        if(jTablePontoTuristico.getSelectedRow() != -1){
            LugaresDAO dao = new LugaresDAO();
            
            int linha = jTablePontoTuristico.getSelectedRow();
            
            if(dao.removerPontoTuristico(Integer.parseInt(jTablePontoTuristico.getValueAt(linha, 0).toString()))){
                ((DefaultTableModel)jTablePontoTuristico.getModel()).removeRow(linha);
                
                JOptionPane.showMessageDialog(null, "Remoção realizada com sucesso!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um destino!");
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        int i = JOptionPane.showConfirmDialog(null, "Deseja voltar sem salvar as alterações?", "Sair", 0);
        
        if(i == 0){ 
            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxContinente;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JLabel jLabelAltaTemporada;
    private javax.swing.JLabel jLabelClima;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelContinente;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelDestinoViagem;
    private javax.swing.JLabel jLabelGo;
    private javax.swing.JLabel jLabelGoImagem;
    private javax.swing.JLabel jLabelIdDestino;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelPassaporte;
    private javax.swing.JLabel jLabelPontosTuristicos;
    private javax.swing.JLabel jLabelRoteiro;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JPanel jPanelPontoTuristico;
    private javax.swing.JScrollPane jScrollPaneAltaTemporada;
    private javax.swing.JScrollPane jScrollPaneClima;
    private javax.swing.JScrollPane jScrollPanePontoTuristico;
    private javax.swing.JTable jTablePontoTuristico;
    private javax.swing.JTextArea jTextAreaAltaTemporada;
    private javax.swing.JTextArea jTextAreaClima;
    private javax.swing.JTextField jTextFieldEntradaDestino;
    // End of variables declaration//GEN-END:variables
}
