package br.inatel.viagens.view;

import br.inatel.viagens.model.dao.LugaresDAO;
import br.inatel.viagens.model.entities.Lugares;
import br.inatel.viagens.model.entities.PontoTuristicoLugares;
import br.inatel.viagens.model.entities.Viagens;
import br.inatel.viagens.util.ConverterTipos;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * @author Nathalya
 * 
 */

public class TelaCriarLugaresAdmin extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaCriarLugaresAdmin() {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jFormattedText.setFocusable(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedText = new javax.swing.JPanel();
        jLabelWorld = new javax.swing.JLabel();
        jLabelRoteiro = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jTextFieldEntradaDestino = new javax.swing.JTextField();
        jLabelPontosTuristicos = new javax.swing.JLabel();
        jLabelNomePontoTuristico = new javax.swing.JLabel();
        jTextFieldEntradaNomePontoTuristico = new javax.swing.JTextField();
        jLabelPrecoPontoTuristico = new javax.swing.JLabel();
        jTextFieldEntradaPrecoPontoTuristico = new javax.swing.JTextField();
        jLabelEnderecoPontoTuristico = new javax.swing.JLabel();
        jTextFieldEntradaEnderecoPontoTuristico = new javax.swing.JTextField();
        jLabelGo = new javax.swing.JLabel();
        jLabelGoImagem = new javax.swing.JLabel();
        jLabelPassaporte = new javax.swing.JLabel();
        jLabelComida = new javax.swing.JLabel();
        jButtonAdicionarPontoTuristico = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelAltaTemporada = new javax.swing.JLabel();
        jScrollPaneAltaTemporada = new javax.swing.JScrollPane();
        jTextAreaAltaTemporada = new javax.swing.JTextArea();
        jLabelClima = new javax.swing.JLabel();
        jScrollPaneClima = new javax.swing.JScrollPane();
        jTextAreaClima = new javax.swing.JTextArea();
        jLabelLatitude = new javax.swing.JLabel();
        jTextFieldEntradaLatitude = new javax.swing.JTextField();
        jLabelLongitude = new javax.swing.JLabel();
        jTextFieldEntradaLongitude = new javax.swing.JTextField();
        jLabelContinente = new javax.swing.JLabel();
        jComboBoxContinente = new javax.swing.JComboBox<>();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuViagem = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World - Criar Roteiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jFormattedText.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedText.setLayout(null);

        jLabelWorld.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logo.png")); // NOI18N
        jFormattedText.add(jLabelWorld);
        jLabelWorld.setBounds(-20, 0, 110, 60);

        jLabelRoteiro.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabelRoteiro.setText("Para onde Viajar?");
        jFormattedText.add(jLabelRoteiro);
        jLabelRoteiro.setBounds(70, 0, 300, 60);

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelInfo.setText("Informações da Viagem:");
        jFormattedText.add(jLabelInfo);
        jLabelInfo.setBounds(60, 75, 230, 30);

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelDestino.setText("Destino:");
        jFormattedText.add(jLabelDestino);
        jLabelDestino.setBounds(20, 170, 50, 30);

        jTextFieldEntradaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaDestino);
        jTextFieldEntradaDestino.setBounds(120, 170, 260, 30);

        jLabelPontosTuristicos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPontosTuristicos.setText("Pontos Turísticos:");
        jFormattedText.add(jLabelPontosTuristicos);
        jLabelPontosTuristicos.setBounds(600, 90, 170, 25);

        jLabelNomePontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNomePontoTuristico.setText("Nome:");
        jFormattedText.add(jLabelNomePontoTuristico);
        jLabelNomePontoTuristico.setBounds(560, 130, 50, 30);

        jTextFieldEntradaNomePontoTuristico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaNomePontoTuristico);
        jTextFieldEntradaNomePontoTuristico.setBounds(620, 130, 310, 30);

        jLabelPrecoPontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelPrecoPontoTuristico.setText("Preço:");
        jFormattedText.add(jLabelPrecoPontoTuristico);
        jLabelPrecoPontoTuristico.setBounds(560, 210, 50, 30);

        jTextFieldEntradaPrecoPontoTuristico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaPrecoPontoTuristico);
        jTextFieldEntradaPrecoPontoTuristico.setBounds(620, 210, 90, 30);

        jLabelEnderecoPontoTuristico.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEnderecoPontoTuristico.setText("Endereço:");
        jFormattedText.add(jLabelEnderecoPontoTuristico);
        jLabelEnderecoPontoTuristico.setBounds(560, 170, 60, 30);

        jTextFieldEntradaEnderecoPontoTuristico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaEnderecoPontoTuristico);
        jTextFieldEntradaEnderecoPontoTuristico.setBounds(620, 170, 310, 30);

        jLabelGo.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelGo.setText("GO!");
        jLabelGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGo);
        jLabelGo.setBounds(870, 550, 50, 40);

        jLabelGoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\plane.png")); // NOI18N
        jLabelGoImagem.setText("jLabel1");
        jLabelGoImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoImagemMouseClicked(evt);
            }
        });
        jFormattedText.add(jLabelGoImagem);
        jLabelGoImagem.setBounds(740, 400, 260, 190);

        jLabelPassaporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\passport.png")); // NOI18N
        jFormattedText.add(jLabelPassaporte);
        jLabelPassaporte.setBounds(20, 70, 50, 40);

        jLabelComida.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\localization.png")); // NOI18N
        jFormattedText.add(jLabelComida);
        jLabelComida.setBounds(560, 70, 30, 60);

        jButtonAdicionarPontoTuristico.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jButtonAdicionarPontoTuristico.setText("  Pontos Turísticos");
        jButtonAdicionarPontoTuristico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarPontoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPontoTuristicoActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonAdicionarPontoTuristico);
        jButtonAdicionarPontoTuristico.setBounds(560, 300, 140, 30);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jFormattedText.add(jButtonVoltar);
        jButtonVoltar.setBounds(840, 20, 90, 30);

        jLabelAltaTemporada.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelAltaTemporada.setText("Alta Temporada:");
        jFormattedText.add(jLabelAltaTemporada);
        jLabelAltaTemporada.setBounds(20, 210, 110, 16);

        jTextAreaAltaTemporada.setColumns(20);
        jTextAreaAltaTemporada.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaAltaTemporada.setRows(5);
        jTextAreaAltaTemporada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jScrollPaneAltaTemporada.setViewportView(jTextAreaAltaTemporada);

        jFormattedText.add(jScrollPaneAltaTemporada);
        jScrollPaneAltaTemporada.setBounds(120, 210, 260, 140);

        jLabelClima.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelClima.setText("Clima:");
        jFormattedText.add(jLabelClima);
        jLabelClima.setBounds(20, 366, 50, 20);

        jTextAreaClima.setColumns(20);
        jTextAreaClima.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaClima.setRows(5);
        jTextAreaClima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jScrollPaneClima.setViewportView(jTextAreaClima);

        jFormattedText.add(jScrollPaneClima);
        jScrollPaneClima.setBounds(120, 360, 260, 140);

        jLabelLatitude.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLatitude.setText("Latitude:");
        jFormattedText.add(jLabelLatitude);
        jLabelLatitude.setBounds(560, 250, 50, 30);

        jTextFieldEntradaLatitude.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLatitude);
        jTextFieldEntradaLatitude.setBounds(620, 250, 90, 30);

        jLabelLongitude.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelLongitude.setText("Longitude:");
        jFormattedText.add(jLabelLongitude);
        jLabelLongitude.setBounds(770, 250, 60, 30);

        jTextFieldEntradaLongitude.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jFormattedText.add(jTextFieldEntradaLongitude);
        jTextFieldEntradaLongitude.setBounds(840, 250, 90, 30);

        jLabelContinente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelContinente.setText("Continente:");
        jFormattedText.add(jLabelContinente);
        jLabelContinente.setBounds(20, 130, 90, 30);

        jComboBoxContinente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "América do Norte", "América do Sul", "Europa", "África", "Oceania", "Ásia" }));
        jFormattedText.add(jComboBoxContinente);
        jComboBoxContinente.setBounds(120, 130, 260, 30);

        jMenuBar.setBackground(new java.awt.Color(74, 39, 72));
        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setForeground(new java.awt.Color(74, 39, 72));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");
        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoMouseClicked
        int continente = jComboBoxContinente.getSelectedIndex() + 1;
        
        Lugares lugar = new Lugares("", "");
        
        lugar.setDestino(jTextFieldEntradaDestino.getText());
        
        Viagens viagem = new Viagens();
        
        jTextAreaAltaTemporada.setLineWrap(true);
        jTextAreaClima.setLineWrap(true);
        
        viagem.setAltaTemporada(jTextAreaAltaTemporada.getText());
        viagem.setClima(jTextAreaClima.getText());
        
        PontoTuristicoLugares pontoTuristico = new PontoTuristicoLugares();
        
        pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico.getText());
        pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico.getText());
        pontoTuristico.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico.getText()));
        
        PontoTuristicoLugares.latitude = Double.parseDouble(jTextFieldEntradaLatitude.getText());
        PontoTuristicoLugares.longitude = Double.parseDouble(jTextFieldEntradaLongitude.getText());
        
        LugaresDAO dao = new LugaresDAO();
        
        if(dao.registrarLugar(continente, lugar, viagem, pontoTuristico)){
            JOptionPane.showMessageDialog(null, "Viagem criada com sucesso!");
            
            new TelaImagem().setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jLabelGoMouseClicked

    private void jLabelGoImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoImagemMouseClicked
        jLabelGoMouseClicked(evt);
    }//GEN-LAST:event_jLabelGoImagemMouseClicked

    private void jButtonAdicionarPontoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPontoTuristicoActionPerformed
        int continente = jComboBoxContinente.getSelectedIndex() + 1;
        
        Lugares lugar = new Lugares("", "");
        
        lugar.setDestino(jTextFieldEntradaDestino.getText());
        
        Viagens viagem = new Viagens();
        
        jTextAreaAltaTemporada.setLineWrap(true);
        jTextAreaClima.setLineWrap(true);
        
        viagem.setAltaTemporada(jTextAreaAltaTemporada.getText());
        viagem.setClima(jTextAreaClima.getText());
        
        PontoTuristicoLugares pontoTuristico = new PontoTuristicoLugares();
        
        pontoTuristico.setNome(jTextFieldEntradaNomePontoTuristico.getText());
        pontoTuristico.setEndereco(jTextFieldEntradaEnderecoPontoTuristico.getText());
        pontoTuristico.setPreco(Double.parseDouble(jTextFieldEntradaPrecoPontoTuristico.getText()));
        
        PontoTuristicoLugares.latitude = Double.parseDouble(jTextFieldEntradaLatitude.getText());
        PontoTuristicoLugares.longitude = Double.parseDouble(jTextFieldEntradaLongitude.getText());
        
        LugaresDAO dao = new LugaresDAO();
        
        if(dao.registrarLugar(continente, lugar, viagem, pontoTuristico)){
            JOptionPane.showMessageDialog(null, "Viagem criada com sucesso!");
            
            new TelaCriarMaisPontosTuristicosViagem(0).setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAdicionarPontoTuristicoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações da viagem?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaListaLugaresAdmin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaListaLugaresAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        int i = JOptionPane.showConfirmDialog(null, "Deseja sair sem salvar as informações da viagem?", "Voltar", 0);
        
        if(i == 0){ 
            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarLugaresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarPontoTuristico;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxContinente;
    private javax.swing.JPanel jFormattedText;
    private javax.swing.JLabel jLabelAltaTemporada;
    private javax.swing.JLabel jLabelClima;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelContinente;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelEnderecoPontoTuristico;
    private javax.swing.JLabel jLabelGo;
    private javax.swing.JLabel jLabelGoImagem;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelLatitude;
    private javax.swing.JLabel jLabelLongitude;
    private javax.swing.JLabel jLabelNomePontoTuristico;
    private javax.swing.JLabel jLabelPassaporte;
    private javax.swing.JLabel jLabelPontosTuristicos;
    private javax.swing.JLabel jLabelPrecoPontoTuristico;
    private javax.swing.JLabel jLabelRoteiro;
    private javax.swing.JLabel jLabelWorld;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JScrollPane jScrollPaneAltaTemporada;
    private javax.swing.JScrollPane jScrollPaneClima;
    private javax.swing.JTextArea jTextAreaAltaTemporada;
    private javax.swing.JTextArea jTextAreaClima;
    private javax.swing.JTextField jTextFieldEntradaDestino;
    private javax.swing.JTextField jTextFieldEntradaEnderecoPontoTuristico;
    private javax.swing.JTextField jTextFieldEntradaLatitude;
    private javax.swing.JTextField jTextFieldEntradaLongitude;
    private javax.swing.JTextField jTextFieldEntradaNomePontoTuristico;
    private javax.swing.JTextField jTextFieldEntradaPrecoPontoTuristico;
    // End of variables declaration//GEN-END:variables
}
