package br.inatel.viagens.view;

/**
 * @author Nathalya
 * 
 */
import br.inatel.viagens.model.dao.LugaresDAO;
import br.inatel.viagens.model.entities.Lugares;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class TelaExibirLugares extends javax.swing.JFrame {
    //Creates new form TelaInicial
    public TelaExibirLugares(int id) {
        initComponents();
        
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        jPanel.setFocusable(true);
        
        jLabelIdContinente.setText(String.valueOf(id));
        
        String continente;
        
        if(id == 1){
            continente = "América do Norte";
        }
        else if(id == 2){
            continente = "América do Sul";
        }
        else if(id == 3){
            continente = "Europa";
        }
        else if(id == 4){
            continente = "África";
        }
        else if(id == 5){
            continente = "Oceania";
        }
        else{ 
            continente = "Ásia";
        }
        jLabelContinente.setText(continente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelContinente = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jButtonVisualizar = new javax.swing.JButton();
        jLabelIdContinente = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPaginaInicial = new javax.swing.JMenu();
        jMenuRoteiro = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemExibir = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItemListaLugares = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel around the World");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(null);

        jLabelContinente.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jPanel.add(jLabelContinente);
        jLabelContinente.setBounds(70, 20, 430, 40);

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel.add(jDesktopPane);
        jDesktopPane.setBounds(70, 100, 600, 460);

        jButtonVisualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jButtonVisualizar.setText("Visualizar");
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonVisualizar);
        jButtonVisualizar.setBounds(690, 100, 100, 30);
        jPanel.add(jLabelIdContinente);
        jLabelIdContinente.setBounds(530, 30, 0, 0);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\comeBack.png")); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonVoltar);
        jButtonVoltar.setBounds(690, 140, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\pontosTuristicos.png")); // NOI18N
        jPanel.add(jLabel2);
        jLabel2.setBounds(680, 250, 330, 320);

        jMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 39, 72)));
        jMenuBar.setPreferredSize(new java.awt.Dimension(225, 35));

        jMenuPaginaInicial.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\home.png")); // NOI18N
        jMenuPaginaInicial.setText("Página Inicial");
        jMenuPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaginaInicialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuPaginaInicial);

        jMenuRoteiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\script.png")); // NOI18N
        jMenuRoteiro.setText("Roteiro");

        jMenuItemCriar.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\add.png")); // NOI18N
        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemCriar);

        jMenuItemExibir.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\view.png")); // NOI18N
        jMenuItemExibir.setText("Exibir");
        jMenuItemExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirActionPerformed(evt);
            }
        });
        jMenuRoteiro.add(jMenuItemExibir);

        jMenuBar.add(jMenuRoteiro);

        jMenuViagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\travel.png")); // NOI18N
        jMenuViagem.setText("Para onde Viajar?");

        jMenuItemListaLugares.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\list.png")); // NOI18N
        jMenuItemListaLugares.setText("Lista de Lugares");
        jMenuViagem.add(jMenuItemListaLugares);

        jMenuBar.add(jMenuViagem);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\NetBeansProjects\\Viagens\\img\\logout.png")); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        new TelaCriarRoteiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jMenuItemExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirActionPerformed
        new TelaExibirTodosRoteiros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemExibirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Lugares.continente = Integer.parseInt(jLabelIdContinente.getText());
        
        //Pega a tela das listas de lugares
        JListCustomRenderer list = new JListCustomRenderer();
        
        //Coloca a tela no DesktopPanel
        jDesktopPane.add(list);
        
        this.setIconImage(new ImageIcon("C:/Users/natha/OneDrive/Documentos/NetBeansProjects/Viagens/img/travel.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed
        int id = Lugares.campoSelecionado;
        
        if(id == -1){
            JOptionPane.showMessageDialog(null, "Selecione um lugar!");
        }
        else{
            LugaresDAO dao = new LugaresDAO();
            
            String destino = dao.buscarDestino(id + 1);
            
            new TelaExibirLugar(destino, id + 1, jLabelIdContinente.getText(), false).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        new TelaContinentes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jMenuPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaginaInicialMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPaginaInicialMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibirLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelContinente;
    private javax.swing.JLabel jLabelIdContinente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemExibir;
    private javax.swing.JMenuItem jMenuItemListaLugares;
    private javax.swing.JMenu jMenuPaginaInicial;
    private javax.swing.JMenu jMenuRoteiro;
    private javax.swing.JMenu jMenuViagem;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
